config/internal/mariadb/deployment.yaml.tmpl, controllers/dspipeline_params.go, controllers/testdata/results/case_1/mariadb/deployment.yaml
Resolves #17 
Unit tests should be sufficient for this change.
=> Parameterize mariadb image.

OWNERS
=> Remove owner.

tests/basictests/dsp-operator.sh
=> Add debug sleep cmd for e2e.

tests/basictests/dsp-operator.sh
=> Add namespaces to dspa e2e tests.

api/v1alpha1/dspipeline_types.go
we were mixing the shorthand and longhand kubebuilder optional validation markers. Standardize on longhand for consistency and clarity.
This change doesn't affect the generated code. It's a no-op style-only change.
=> use longhand kubebuilder optional validation markers

tests/basictests/dsp-operator.sh
=> Add debug sleep statement for ci testing.

OWNERS
=> add user to owners.

tests/basictests/dsp-operator.sh
=> Add ci debug commands.

tests/basictests/dsp-operator.sh
Fix the e2e tests with inclusion of pre-existing pipeline
As the dspo installation includes demo flip coin example, the total number of pipelines is to be changed.
Tested as standard e2e tests , connecting to a cluster and using manual commands.
```
cd tests
make build
make run
```
=> Fix the e2e tests with inclusion of pre-existing pipeline

OWNERS
Include as an OWNER for dspo
With the recent inclusion on the project, 
i would like to extend my assistance to reviewing and merging of PR.
This PR would allow me to be an approver
Not as a code change.
=> Include as an approver for dspo

config/rbac/aggregate_dspa_role.yaml, config/rbac/kustomization.yaml
Resolve: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/71
`make deploy`, log in as user with `admin` or `edit` role, create/delete DSPA.
=> Allow admin/edit roles to crud dspa.

config/manager/manager.yaml
Based on our performance testing, dspo with 4Gi memory and current cpu allotment can handle upwards of ~2k OCP users submitting DSPA's.
=> Up dspo memory to handle more users.

.github/workflows/pr-close-image-delete.yml, .github/workflows/tag-release-quay.yml
Github action: Maintain consistency in var names
Just maintaining the same variable name across the github workflow
Pre-tested on fork.
=> Github action: Maintain consistency in var names

controllers/config/defaults.go, controllers/dspipeline_controller.go
This change will remove some conditions from DSPA CR.
1. Deploy the DSP Operator
2. Deploy a DSPA CR without the UI
3. Check if the following conditions are present:
* APIServerReady
* PersistenceAgentReady
* ScheduledWorkflowReady
* Ready
=> Remove some conditions in DSPA

config/samples/dspa_all_fields.yaml, config/samples/dspa_simple_external_storage.yaml
update the sample configs to use updated values
n/a
cc @HumairAK
=> update sample config aws secret key values

tests/basictests/dsp-operator.sh
Adding end to end tests for DSPO that test experiments
- Deploy a DSPA instance
- Run the following commands:
- `make build` -- to create the test container image
-  `make run TESTS_REGEX=ml-pipelines`
-  This will run the container image locally
-  It will further apply the kfdef defined in the `kfctl_openshift.yaml` file.
- If you have the kfdef installed already, you can run this instead:
`make run SKIP_INSTALL=true SKIP_KFDEF_INSTALL=true`
=> Add tests for DSP experiments

tests/basictests/dsp-operator.sh
e2e: 5m sleep waiting for pods to come up had no effect, move it up
=> e2e: 5m sleep waiting for pods to come up had no effect, move it up

kfdef/README.md, kfdef/kfdef.yaml
Add a sample kfdef with instructions to deploy latest dspo in this repo from main branch.
Install ODH, follow readme instructions in pr.
=> Add a kfdef that deploys latest dspo.

config/internal/apiserver/sample-config.yaml.tmpl, config/internal/apiserver/sample-pipeline.yaml.tmpl, controllers/testdata/declarative/case_2/expected/created/sample-config.yaml.tmpl, controllers/testdata/declarative/case_2/expected/created/sample-pipeline.yaml.tmpl
Update images used in sample pipeline to use UBI-based images
Updates the busybox and python images to utilize UBI images
Deploy DSPO from PR codebase.  Create a simple DSPA and verify the images used in the sample pipeline are now ubi-minimal and ubi-python
=> Fix sample pipeline images

controllers/dspipeline_controller.go
* Add logging of dspa namespace to metrics logging  (fix https://github.com/opendatahub-io/data-science-pipelines-operator/issues/123)
* Update statuses for dspa when components are scaled down (fix https://github.com/opendatahub-io/data-science-pipelines-operator/issues/122)
=> Fix statuses

config/manager/manager-service.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
This reverts commit 374f86b544f0376f43a7c2e92cdc30d57b6fbb78.
JIRA link: https://issues.redhat.com/browse/RHODS-8935
=> Revert "Update DSP Operator labels"

README.md
=> Update OCP pipelines pre-req version req.

config/manager/manager-service.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
This reverts commit 90524c44bd510e2e58c8b73689bdd1eeea76f335.
Related task: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/140
=> Update DSP Operator labels

config/internal/apiserver/role_pipeline-runner.yaml.tmpl
Resolve: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/158
=> Give pipeline runner access to mcad/ray res.

config/rbac/role.yaml
Follow up to: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/158
=> Provide dspo with rbac needed to hand out mcad/ray perms.

controllers/config/templating.go
Update templating name from "foo" to "manifestTemplateDSP"
Ref: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/16
Update templating name from "foo" to "manifestTemplateDSP"
=> Fix: update template name to be more unique

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
Add bug report and feature request issue forms.
Credit to odh-dashboard for some of this as I took [their](https://github.com/opendatahub-io/odh-dashboard/tree/main/.github/ISSUE_TEMPLATE) forms as inspiration.
Preview: https://github.com/HumairAK/data-science-pipelines-operator/issues/new/choose
=> Add issue forms for dspo.

.github/PULL_REQUEST_TEMPLATE.md
Add a PR template that specifically prompts for resolving issue.
=> Add pr template.

Makefile
Resolves #<issue_number>
Raised the PR to build on Power as kustomize version = 5.1.0 is supported on Power
=> Update Makefile for power kustomize change

.github/workflows/odh-manifests-PR-sync.yml
=> Turn off on tag push event for odh-manifests PR sync action

.github/workflows/tag-release-quay.yml
Related https://github.com/opendatahub-io/data-science-pipelines-operator/issues/177
=> Turn of auto image tagging for dspo.

OWNERS
This is just to add amadhusu as Reviewer and doesn't resolve any issue as such.
Added amadhusu as Reviewer
N/A
=> Added amadhusu as Reviewer

.github/workflows/tag-and-build.yml
Furhters https://github.com/opendatahub-io/data-science-pipelines-operator/issues/177
Add image builds via gh actions.
Tested here in my fork and quay  account: https://github.com/HumairAK/data-science-pipelines-operator/actions/runs/5694639564
=> Add workflow for src image build and push to tag.

.github/workflows/odh-manifests-PR-sync.yml
Follow up to https://github.com/opendatahub-io/data-science-pipelines-operator/issues/178
=> Allow odh sync to fork from user fork.

.github/workflows/odh-manifests-PR-sync.yml
Cherry-pick from 40ce94c3e41d73756f1364ee7951922a5956cc42
=> [Cherry Pick][v1.2.x] 40ce94c3e41d73756f1364ee7951922a5956cc42

.github/workflows/odh-manifests-PR-sync.yml
Cherry-pick from https://github.com/opendatahub-io/data-science-pipelines-operator/commit/841563119236c2afd425b384252803288033aae2
=> [Cherry Pick][v1.2.x] 8415631

.github/workflows/odh-manifests-PR-sync.yml
=> Add branch inputs and fix repo name in PR sync GH workflow

OWNERS
=> Add DharmitD to DSPO approvers

README.md
The "Installation" link is broken. This PR fixes that.
=> Fixed "Installation" link

.github/workflows/build-prs.yml
The inputs were initially incorrect, so action event wasn't being transferred correctly.
=> Correct gh pr trigger inputs.

.github/workflows/release_create.yaml
=> Correct org mention in release notes links.

controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Related https://github.com/opendatahub-io/data-science-pipelines-operator/issues/294
=> Correct artifact endpoints/bucket for test cases.

config/internal/apiserver/artifact_script.yaml.tmpl, controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/294 for v1.1
=> [cherry-pick] 64edd6d -> V1.1.x

config/internal/apiserver/artifact_script.yaml.tmpl, controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml, controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/294 for v1.2
=> [cherry-pick] 64edd6d -> V1.2.x

.github/workflows/functests.yml, .github/workflows/unittests.yml, .pre-commit-config.yaml
Resolves #284 
- Remove old pre-commit go-unit-test check (doesn't work with new tags used in tests)
- Add Unit Test GitHub Action
- Add Functional Test GitHub Action
Verify the Checks on this PR pass :)
=> Fix Testing GitHub Actions

.github/workflows/functests.yml, .github/workflows/unittests.yml
Update the Unit and Functional Test names to be slightly more concise
Make sure the GH Actions are Named 'Unit Tests' and 'Functional Tests'
=> Improve GitHub Testing Actions names

controllers/config/defaults.go, controllers/database.go, controllers/dspipeline_controller.go, controllers/storage.go
Cherry-pick from 7fa05100892187b5962542b62a62c8340aefef45, cd4bcf09c260deccd00253e8f0a0ca8c49231420
=> Add timeout to db/storage health checks, increase reconcile concurrency

.github/actions/kind/action.yml
=> Fixing Kind yaml path

.github/workflows/add-issues-to-odh-project.yml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/351
=> Add gh workflow to auto add issues to proj.

api/v1alpha1/dspipeline_types.go, config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/200
Added descriptive comments to DSPASpec
1. Deploly DSPO/DSPA
2. Navigate to DSPA in OCP console API Explorer, mouse over the affected fields and confirm the descriptions shows up.
=> Added descriptive comments to DSPASpec

.github/workflows/functests.yml, .github/workflows/precommit.yml, .github/workflows/unittests.yml, Dockerfile, controllers/testutil/util.go, go.mod
Resolves #395 
Upgrades Golang version from 1.18 to 1.19
- First, verify `make test`, assert unit and func tests pass (as well as CI on GitHub).
- Build via `make build`
- Run via `make run`, or `go run bin/manager -config=$configfile` assuming config file exists
=> Upgrade to Go 1.19

OWNERS
Opt out as reviewers for data-science-pipeline-operator
Resolves #<issue_number>
Not sure, if this is mandatory.
As my focus has shifted a bit, I haven't been able to provide total support in reviewing the PRs.
I want to opt-out as a reviewer for now and continue acting as a contributor going forward.
Thank you to the team.
NA
=> Opt out as reviewers for data-science-pipeline-operator

README.md
Resolves #159
Added new section with Deployment and testing process for developers.
=> Added new section for Deployment and testing guidelines for Developers

Dockerfile, kfdef/kfdef.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/392
This PR updates the ubi-minimal, go-toolset, go-toolset, ubi and ose container images.
=> Updated ubi-minimal, go-toolset, go-toolset, ubi and ose images

config/internal/apiserver/deployment.yaml.tmpl, config/internal/apiserver/monitor.yaml.tmpl, config/internal/apiserver/role_ds-pipeline-user-access.yaml.tmpl, config/internal/apiserver/role_ds-pipeline.yaml.tmpl, config/internal/apiserver/role_pipeline-runner.yaml.tmpl, config/internal/apiserver/rolebinding_ds-pipeline.yaml.tmpl, config/internal/apiserver/rolebinding_pipeline-runner.yaml.tmpl, config/internal/apiserver/route.yaml.tmpl, config/internal/apiserver/sa_ds-pipeline.yaml.tmpl, config/internal/apiserver/sa_pipeline-runner.yaml.tmpl, config/internal/apiserver/sample-config.yaml.tmpl, config/internal/apiserver/sample-pipeline.yaml.tmpl, config/internal/apiserver/service.yaml.tmpl, config/internal/common/policy.yaml.tmpl, config/internal/persistence-agent/deployment.yaml.tmpl, config/internal/persistence-agent/role.yaml.tmpl, config/internal/persistence-agent/rolebinding.yaml.tmpl, config/internal/persistence-agent/sa.yaml.tmpl, config/internal/scheduled-workflow/deployment.yaml.tmpl, config/internal/scheduled-workflow/role.yaml.tmpl, config/internal/scheduled-workflow/rolebinding.yaml.tmpl, config/internal/scheduled-workflow/sa.yaml.tmpl, controllers/apiserver.go, controllers/apiserver_test.go, controllers/dspipeline_controller.go, controllers/dspipeline_params.go, controllers/persistence_agent.go, controllers/persistence_agent_test.go, controllers/scheduled_workflow.go, controllers/scheduled_workflow_test.go
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/165
This PR adds better variable handling of DSPO deployed manifest names and improves tests by ensuring readiness is being properly handled
`make unittest`
=> Added better variable handling of DSPO deployed manifest names

controllers/dspipeline_controller.go
Resolves #164
Created a map to use in the PublishMetrics function instead of using a set of functions.
Clone the repo and deploy DSPO and then create a DSPA instance, the metrics should be displayed like before.
=> Update Metrics publish to accept a boundless number of conditions to publish

config/samples/dspa_simple_v2.yaml
First pass on a simple sample dspa.
=> Add a sample dspa for v2.

controllers/dspipeline_controller.go, controllers/storage.go
=> fix: DSPO crashes when external connections failed

api/v1alpha1/dspipeline_types.go, config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml, controllers/dspipeline_params.go, controllers/storage.go, controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_7/expected/created/minio_deployment.yaml, controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
Work around to make storage artifact passing work until  https://github.com/opendatahub-io/data-science-pipelines-operator/issues/494 is resolved.
=> Add workaround to fix artifact passing

README.md
Update Pre-requisites to Openshift 4.11+
=> Update Pre-requisites to Openshift 4.11+

config/samples/dspa_simple_v2.yaml
```
make deploy argodeploy
oc new-project kubeflow
make deploy
oc -n kubeflow apply -f config/samples/dspa_simple_v2.yaml
```
=> chore: further simplify v2 simple dspa example.

tests/README.md
Resolves #annonyance
Fix doc to refer to correct namespace operator is deployed to by default
(proof)read the docs :)
=> Fix namespace reference in Integration Test docs

.github/workflows/build-tags.yml
Update build sources for v2 images.
=> add v2 image sources and update paths.

datasciencecluster/datasciencecluster.yaml
...and remove dashboard in dsc
=> enable management state for dsc.

config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl, controllers/testdata/declarative/case_7/expected/created/sample-pipeline.yaml.tmpl
The dockerfile for this is simply: 
```
FROM quay.io/rmartine/data-science:test9
USER root
WORKDIR /
RUN mkdir s3 gs
RUN chgrp -R 0 /.cache && \
chmod -R g=u /.cache && \
chgrp -R 0 /tmp/kfp && \
chmod -R g=u /tmp/kfp && \
chgrp -R 0 /.local && \
chmod -R g=u /.local && \
chgrp -R 0 /minio && \
chmod -R g=u /minio && \
chgrp -R 0 /s3 && \
chmod -R g=u /s3 && \
chgrp -R 0 /gs && \
chmod -R g=u /gs
USER 1001
```
=> update iris pipeline image in sample

config/samples/dspa_simple_v2.yaml
=> remove workflowcontroller from simple dspa v2.

.github/workflows/build-prs-trigger.yaml, .github/workflows/kind-integration.yml, go.mod
Resolves https://issues.redhat.com/browse/RHOAIENG-2259
Fixing go.opentelemetry.io/contrib dependency related snyk CVE.
Made this change on my fork (correctly rebased to and snyced with the remote's main) 
Ran `go mod tidy` 
Imported my fork in synk and made sure the relevant CVEs were fixed with this update.
Deploy a pipeline and make sure everything works as expected.
=> Fix go.opentelemetry.io/contrib CVE

README.md
Resolves [RHOAIENG-1718](https://issues.redhat.com/browse/RHOAIENG-1718)
=> Update README pre-requistes to add Argo workflows installation details

.github/workflows/build-prs.yml
NA
Add an instruction to create a project before doing the deploy.
Execute the steps into that section
- [ x ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ x ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x ] The developer has manually tested the changes and verified that the changes work
=> Create project before deploy

config/internal/apiserver/server-config.yaml.tmpl
Resolves # https://issues.redhat.com/browse/RHOAIENG-4509
=> chore: revert default obj store pipeline save path

.pre-commit-config.yaml, Makefile, controllers/dspipeline_fake_controller.go, controllers/dspipeline_params.go, controllers/dspipeline_params_test.go, controllers/testdata/tls/dummy-ca-bundle.crt, controllers/testutil/util.go
Add unit tests for cabundle cases for params
=> Add params unittest cases for cabundle

api/v1alpha1/dspipeline_types.go, config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml, config/internal/workflow-controller/deployment.yaml.tmpl, config/samples/v2/custom-workflow-controller-config/custom-workflow-controller-configmap.yaml, config/samples/v2/custom-workflow-controller-config/dspa.yaml, config/samples/v2/custom-workflow-controller-config/kustomization.yaml
Resolves https://issues.redhat.com/browse/RHOAIENG-5287
Added CustomConfig to WorkflowController.
Deploy config/samples/v2/custom-workflow-controller-config and run a pipeline. The pipeline must complete successfully.
=> Added CustomConfig to WorkflowController

controllers/dspipeline_controller_func_test.go, controllers/suite_test.go, controllers/testutil/util.go, go.mod, go.sum
Resolves https://issues.redhat.com/browse/RHOAIENG-4261
Replaced Ginkgo and Gomega with Testify in functional tests
Run `make test`. All tests must pass.
=> Replaced Ginkgo and Gomega with Testify in functional tests

scripts/release/params.py
Futrhers https://issues.redhat.com/browse/RHOAIENG-4251
In v2 we added new images, and since then various new options to the config, this change updates the params file generator used for creating releases to account for these changes.
=> chore: fix params generator for v2

Dockerfile
Resolves [RHOAIENG-7423](https://issues.redhat.com/browse/RHOAIENG-7423)
Updated ubi8 image as suggested in [RHOAIENG-7423](https://issues.redhat.com//browse/RHOAIENG-7423)
Sanity Tests
=> RHOAIENG-7423 - Updated ubi8 image

tests/pipeline_runs_test.go
=> Fixed typo

.github/build/Dockerfile, .github/workflows/functests.yml, .github/workflows/kind-integration.yml, .github/workflows/precommit.yml, .github/workflows/unittests.yml, Dockerfile, go.mod, go.sum
Resolves https://issues.redhat.com/browse/RHOAIENG-8475
=> Update go toolset version to 1.21

config/samples/v1/custom-configs/dspa.yaml, config/samples/v1/dspa-all-fields/dspa_all_fields.yaml, config/samples/v1/dspa-local-dev/dspa_local_dev.yaml, config/samples/v1/dspa-simple/dspa_simple.yaml, config/samples/v1/external-object-storage/dspa.yaml, config/samples/v2/custom-configs/dspa.yaml, config/samples/v2/custom-workflow-controller-config/dspa.yaml, config/samples/v2/dspa-all-fields/dspa_all_fields.yaml, config/samples/v2/dspa-simple/dspa_simple.yaml, config/samples/v2/external-object-storage/dspa.yaml, config/samples/v2/local-dev/dspa.yaml
Resolves https://issues.redhat.com/browse/RHOAIENG-6580
This PR enables the sample pipeline in DSPA samples.
Deploy a DSPA sample and the sample pipeline must be present.
=> Enabled sample pipeline in DSPA samples

.github/resources/dspa-lite/dspa.yaml, .github/resources/mariadb/deployment.yaml, tests/resources/dspa-lite.yaml
=> increase integration db resources

api/v1alpha1/dspipeline_types.go, config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml, controllers/config/defaults.go, controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_9/expected/created/apiserver_deployment.yaml
cherry-pick: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/676
=> [cherry-pick] increase default expiry for signed url

controllers/testutil/util.go
This PR:
- Adds a log message with the error that occurred when waiting for resources to get ready on functional tests.
- Changes verifications from `assert` to `require` in `controllers/testutil/util.go#CompareResources`.
```
2024-08-29T11:35:25-03:00	INFO	Error when trying to get ds-pipeline-ui-testdsp9 (will keep trying until reaching timeout): deployments.apps "ds-pipeline-ui-testdsp9" not found
```
=> chore: Improved logs for tests

OWNERS
Add anishasthana
Move accorvin to emeritus
Remove amudhusu from reviewers
=> OWNERS updates

config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
Resolves https://issues.redhat.com/browse/RHOAIENG-13630
Added secrets::list permissions to pipeline runner
Run a Ray Integration pipeline
=> Added secrets::list permissions to pipeline runner

config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
Cherry Pick: https://github.com/opendatahub-io/data-science-pipelines-operator/commit/2e3409fed19f47928d26dec841c1b7feb5df5e2a
=> Cherry Pick: 2e3409

README.md
Resolves #annoyance
Add context and improve grammar of prereqs and installation instructions in README
RTD
=> chore: Fix typos and improve grammar of README.md

docs/release/compatibility.md, docs/release/compatibility.yaml
For upcoming 2.7 release, update compatibility doc.
=> update compatibility doc for 2.7

tests/dspa_v2_test.go
This PR adds a retry for an integration test that fails for not having all pods running.
CI must pass.
=> Added retry for integration test

config/internal/persistence-agent/deployment.yaml.tmpl
Signed-off-by: Helber Belmiro <helber.belmiro@gmail.com>
(cherry picked from commit 40ca5edae1a86e7460e9c86a0de4de15664c95d4)
=> Use DSPA custom ca cert on MLMD and Persistence Agent clients

controllers/dspipeline_params.go, tests/dspa_v2_test.go, tests/resources/test-pipeline-run.yaml, tests/resources/test-pipeline-with-custom-pip-server-run.yaml
This PR cherry-picks the following changes:
- https://github.com/opendatahub-io/data-science-pipelines-operator/pull/742
- https://github.com/opendatahub-io/data-science-pipelines-operator/pull/745
- https://github.com/opendatahub-io/data-science-pipelines-operator/pull/737
=> Cherry-pick a8da75c, f10945b and 0e775db

config/internal/ml-metadata/metadata-grpc-tls-config-secret.yaml.tmpl
Signed-off-by: Helber Belmiro <helber.belmiro@gmail.com>
(cherry picked from commit bacb3e3d97a989850bae04048e8a761fce67ff46)
=> Removed comment from MLMD gRPC server config

.github/scripts/tests/collect_logs.sh, .github/workflows/kind-integration.yml
Resolves https://issues.redhat.com/browse/RHOAIENG-15408
This PR improves troubleshooting of integration tests by adding logs and event collection on failures
See how logs are shown in https://github.com/opendatahub-io/data-science-pipelines-operator/actions/runs/11843866900/job/33005780225?pr=747#step:6:1
=> Added logs and event collection on integration test failures

.github/scripts/tests/README.md
Resolves #[RHOAIENG-15407](https://issues.redhat.com//browse/RHOAIENG-15407)
Document how to run the test suite locally
Read and execute the README.md commands
=> How run the test suite locally

.github/actions/kind/action.yml, .github/workflows/kind-integration.yml
=> Bump k8s version to 1.30

.github/scripts/tests/README.md, README.md
Resolves #[RHOAIENG-15407](https://issues.redhat.com//browse/RHOAIENG-15407)
How to debug using GoLand
NA
=> How to debug using GoLand

api/v1/dspipeline_types.go, api/v1alpha1/dspipeline_types.go, config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml, config/internal/apiserver/default/deployment.yaml.tmpl, config/internal/apiserver/sample-pipeline/sample-config.yaml.tmpl, controllers/apiserver.go, controllers/dspipeline_params.go, tests/pipeline_test.go, tests/resources/dspa-lite.yaml, tests/resources/test-pipeline-run.yaml, tests/resources/test-pipeline-with-custom-pip-server-run.yaml, tests/util/rest.go
Reverts opendatahub-io/data-science-pipelines-operator#764
Context: Need to delay this for 1 release to introduce the new api changes in-sync with platform operator
=> Revert "Add ilab kfp pipeline to the DSPO repo"

docs/release/compatibility.md, docs/release/compatibility.yaml
=> update compatibility doc for 2.9

.github/workflows/build-prs-trigger.yaml, .github/workflows/build-prs.yml, .github/workflows/release_create.yaml, .github/workflows/release_trigger.yaml
Update upload-artifact, this requires also an update to the donwload artifact script and code changes.
=> update upload-artifact in gh ci

go.mod, go.sum
glog upgraded to 1.2.4 fixes CVE GO-2025-3372
=> fix: glog upgraded to 1.2.4 fixes CVE GO-2025-3372

config/overlays/make-deploy/kustomization.yaml
=> Revert make-deploy overlay to use ODH:main image

config/configmaps/files/config.yaml, config/internal/apiserver/default/deployment.yaml.tmpl, controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Updates reference to compiled-in-time version of instructlab pipeline
=> fix: Update InstructLab pipeline filepath reference

.github/workflows/precommit.yml
This PR upgrades actions/cache to v4, since [v2 is deprecated](https://github.com/opendatahub-io/data-science-pipelines-operator/actions/runs/13396877789/job/37418012709?pr=779).
CI should pass.
=> Upgraded actions/cache to v4

config/internal/apiserver/default/deployment.yaml.tmpl, controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml, controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
This is required for the `upload_model_op` component in the InstructLab pipeline.
=> Replace the generic runtime image in the InstructLab pipeline

config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
Once failure [here](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/811) is confirmed, this will fix the issue, ci passing is sufficient here for a confirmation
=> replace iris data set with working link

proposals/bring_your_own_argo_workflows/byoaw_test_plan.md
~- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).~
~- [ ] The developer has manually tested the changes and verified that the changes work~
=> docs(test): moving all tests to dspo

config/base/params.env
=> updating DSPA's images with their respective shas
