- controllers/config/templating.go
This fixes the staticheck pre-commit test failure that occurs locally, not sure why it's ignored via the github action, but will follow up a fix on that next.
> Use io from io pkg instead of deprecated ioutil.

- .github/build/Dockerfile
- .github/workflows/precommit.yml
- README.md
- config/crd/external/route.openshift.io_routes.yaml
- config/internal/apiserver/service.yaml.tmpl
- config/internal/mlpipelines-ui/route.yaml.tmpl
- controllers/apiserver.go
- controllers/database.go
- controllers/dspipeline_controller.go
- controllers/dspipeline_controller_test.go
- controllers/mlpipeline_ui.go
- controllers/persistence_agent.go
- controllers/scheduled_workflow.go
- controllers/storage.go
- controllers/suite_test.go
- controllers/testdata/deploy/case_1.yaml
- controllers/testdata/results/case_1/apiserver/deployment.yaml
- controllers/testdata/results/case_1/mariadb/deployment.yaml
- controllers/testdata/results/case_1/minio/deployment.yaml
- controllers/testdata/results/case_1/mlpipelines-ui/deployment.yaml
- controllers/testdata/results/case_1/persistence-agent/deployment.yaml
- controllers/testdata/results/case_1/scheduled-workflow/deployment.yaml
- controllers/testdata/results/case_1/viewer-crd/deployment.yaml
- controllers/testutil/util.go
- controllers/viewer_crd.go
- go.mod
- go.sum
- main.go
Add unit tests for dsp operator. Adds about ~75% coverage, tests currently only compare deployments but can be extended to other resources. Code was updated to accommodate unit testing, like allowing the ability to specify template manifests.
See tests running in my example in my fork [here](https://github.com/HumairAK/data-science-pipelines-operator/actions/runs/4139249101/jobs/7156610600).
> Add unit testing.

- main.go
change log output to have human readable times (RFC3339 instead of epoch)
build image, ran it in my dev cluster:
```
2023-02-13T21:15:20Z	DEBUG	events	data-science-pipelines-operator-controller-manager-84d5d4bcwhp7_7b84c00b-fa2a-4001-80ae-6f059785ebd8 became leader	<snip>
```
/assign @HumairAK
> change log output to have human readable times

- Dockerfile
the kubebuilder scaffolding uses gcr.io/distroless/static:nonroot but we switched to UBI in 15c7376. So removing old comment.
> remove outdated comment about distroless base image

- Dockerfile
specifying `USER 65532:65532` is a distroless image thing and not required for UBI, which we switched to in 15c7376.
I built the image with this change and deployed it to my test cluster. Everything still works fine.
> remove nonroot user 65532

- config/samples/dspipelines.io_v1alpha1_dspipeline.yaml
Proposal for updated CR Spec. Please provide your thoughts on what else is required here, and we will follow up with code chances to accomodate the new sample spec. 
The `deploy: true` is to allow us to disable components for development purposes, for example, we may want to deploy apiserver locally while wanting to deploy the rest of the stack via operator.
I'm thinking the most minimal spec would be: 
```yaml
apiVersion: dspipelines.opendatahub.io/v1alpha1
kind: DSPipeline
metadata:
name: sample
namespace: data-science-project
spec:
apiServer:
deploy: true
persistentAgent:
deploy: true
scheduledWorkflow:
deploy: true
viewerCRD:
deploy: true
mlpipelineUI:
deploy: true
database:
mariaDB:
deploy: true
storage:
minio:
deploy: true
```
And everything else is optional with default values.
> Propose new cr spec.

- config/samples/dspipelines.io_v1alpha1_dspipeline.yaml
- config/samples/dspipelines_proposed.yaml
- controllers/dspipeline_controller_test.go
- controllers/dspipeline_params.go
- controllers/testdata/deploy/case_2.yaml
- controllers/testdata/results/case_1/apiserver/configmap_artifact_script.yaml
- controllers/testdata/results/case_2/apiserver/configmap_artifact_script.yaml
- controllers/testutil/util.go
This change will make it so api server will fail to deploy if a custom artifact script provided by the user does not exist. Furthermore, it will also ensure that the default artifact script follows naming conventions that are consistent with the rest of the namespace scoped resources. Tests are addded to accomodate this change.
Resolve #19 
Via unit tests, and live ocp cluster.
> Improve custom artifact script handling.

- config/base/kustomization.yaml
- config/prometheus/monitor.yaml
Created a Service to expose DSP Operator SDK metrics in https://github.com/opendatahub-io/data-science-pipelines-operator/pull/22
Adding a ServiceMonitor for Data Science Pipelines Operator, with labels matching to the above service config.
Tested out on a local cluster with both the service and the ServiceMonitor configs applied, metrics were found to be scraped by Prometheus:
> Adding a ServiceMonitor for Data Science Pipelines Operator

- config/manager/kustomization.yaml
- config/manager/manager-service.yaml
Adding a service to expose Operator SDK metrics port
On a test cluster:
- Added this service config
- Port forwarded to the localhost port via the service:
`oc port-forward svc/data-science-pipelines-operator 8080:8080 -n data-science-pipelines-operator`
- Curled to the localhost to retrieve a list of Operator SDK metrics:
`curl -v http://localhost:8080/metrics`
Find a list of metrics returned by the curl command [here.](http://pastebin.test.redhat.com/1092224)
> Adding a service to expose Operator SDK metrics

- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- config/internal/mlpipelines-ui/role.yaml.tmpl
- controllers/testdata/results/case_0/mlpipelines-ui/deployment.yaml
- controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
Updates to have auth permission for OAuth-proxy, which would allow SA to authenticate.
As most of times, we use the Openshift cluster above 4.9 version, the image update to oauth-proxy is also needed
as TokenReview API change is addressed in newer images.
- This includes new image update
- Providing more specific information on oauth proxy delegation 
- Inclusion of role missing for the SA.
Tested the change by deploying operator using this PR image `quay.io/opendatahub/data-science-pipelines-operator:pr-26`
and send request to the UI routes.
`TOKEN=$(oc create token ds-pipeline-ui-sample -n <namespace>)`
`curl -k -H "Authorization: Bearer $TOKEN"  https://<route-url>/apis/v1beta1/pipelines`
> Updates to have auth permission for oauth proxy

- tests/basictests/dsp-operator.sh
- tests/resources/dsp-operator/test-dspo-cr.yaml
Include metrics testing in E2E tests
Included metrics testing check as a part of E2E tests, as mentioned in Note here:https://github.com/opendatahub-io/data-science-pipelines-operator/pull/23#issue-1593637302
- Adjusted Token creation for SA as per cluster rules.
with the help of makefile and openshift cluster, try the following:
```
cd tests
make build
make run
```
Tested on openshift cluster with version: 4.12.2
> Include metrics testing in E2E tests

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
the new CRD name `datasciencepipelinesapplications` is a bit long. Add a shortName `dspa`.
ran `make test`, deployed it to a cluster and ran `k get dspa`
> add shortName for datasciencepipelinesapplications

- config/configmaps/files/config.yaml
- config/manager/manager.yaml
- controllers/testdata/deploy/case_0/config.yaml
- controllers/testdata/deploy/case_1/config.yaml
- controllers/testdata/deploy/case_2/config.yaml
- controllers/testdata/deploy/case_2/cr.yaml
- controllers/testdata/deploy/case_3/config.yaml
- controllers/testdata/deploy/case_3/cr.yaml
- controllers/testdata/results/case_0/apiserver/deployment.yaml
- controllers/testdata/results/case_0/mariadb/deployment.yaml
- controllers/testdata/results/case_0/minio/deployment.yaml
- controllers/testdata/results/case_0/mlpipelines-ui/deployment.yaml
- controllers/testdata/results/case_0/persistence-agent/deployment.yaml
- controllers/testdata/results/case_0/scheduled-workflow/deployment.yaml
- controllers/testdata/results/case_0/viewer-crd/deployment.yaml
- controllers/testdata/results/case_2/apiserver/deployment.yaml
- controllers/testdata/results/case_2/mariadb/deployment.yaml
- controllers/testdata/results/case_2/minio/deployment.yaml
- controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
- controllers/testdata/results/case_2/persistence-agent/deployment.yaml
- controllers/testdata/results/case_2/scheduled-workflow/deployment.yaml
- controllers/testdata/results/case_2/viewer-crd/deployment.yaml
- controllers/testdata/results/case_3/apiserver/deployment.yaml
Also update apiserver image to latest version that allows one to set the
move-results-image. Unfortunately the other components do not have an
image cut for v1.22 so the closest we can get is 1.20, they will be
brought in sync in a follow up change.
Locally and on OCP OSD with: quay.io/hukhan/data-science-pipelines-operator:v0.0.9
Run unit tests on this pr by cloning the branch and following instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#run-tests). 
Deploy on dev cluster with ocp pipelines (logged in as cluster admin): 
```
oc new-project data-science-pipelines-operator
make podman-build podman-push IMG=$YOUR_CONTAINER_REPO
make deploy IMG=$YOUR_CONTAINER_REPO
```
Deploy a sample cr with the updated resource kind: 
```yaml
apiVersion: …
```
> Replace busybox img

- tests/resources/dsp-operator/test-dspo-cr.yaml
This way we don't need to keep making sure the e2e test cr is upto date with spec. 
It has not, we need it to go into ci here to test: https://github.com/openshift/release/pull/37079
> Use empty cr for e2e tests.

- config/base/kustomization.yaml
- config/base/params.env
- config/base/params.yaml
- config/configmaps/files/config.yaml
- config/manager/manager.yaml
This change will allos a user to deploy dspo via a kfdef and specify image parameters within the kfdef to be used for the DSPA components.
With ODH installed via Olm, deploy this kfdef: 
<details> 
<summary> kfdef.yaml </summary>
```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: data-science-pipelines-operator
namespace: data-science-pipelines-operator
spec:
applications:
- kustomizeConfig:
parameters:
- name: IMAGES_APISERVER
value: BLAHBLAH
- name: IMAGES_ARTIFACT
value: BLAHBLAH1
- name: IMAGES_PERSISTENTAGENT
value: BLAHBLAH2
- name: IMAGES_SCHEDULEDWORKFLOW
value: BLAHBLAH3
- name: IMAGES_VIEWERCRD
value: BLAHBLAH4
- name: IMAGES_CACHE
value: BLAHBLAH5
- name: IMAGES_MOVERESULTSIMAGE
value: BLAHBLAH6
- name: IMAGES_MLPIPELINEUI
value: BLAHBLAH7
- name: …
```
> Add kfdef image parameters.

- Makefile
- README.md
- config/base/kustomization.yaml
We do not want to enforce a single namespace for dspo make deploy/undeploy command, user should be free to target whichever namespace with ease. Default ns remains the same.
The change also updates image latest to `main` since we do not have this tag currently and latest changes are going to `main` branch. To keep it `latest` we'll need to consult with our ci expert  @harshad16  and make the necessary changes, for now this will get it working again.
simply run make deploy / make undeploy
> Add target ns to make deploy/undeploy.

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/deployment.yaml.tmpl
- config/internal/apiserver/route.yaml.tmpl
- config/internal/apiserver/sa_ds-pipeline.yaml.tmpl
- config/internal/apiserver/service.yaml.tmpl
- config/internal/common/clusterrolebinding.yaml.tmpl
- config/internal/common/policy.yaml.tmpl
- config/rbac/role.yaml
- controllers/apiserver.go
- controllers/common.go
- controllers/dspipeline_controller.go
- controllers/mlpipeline_ui.go
- controllers/testdata/deploy/case_2/cr.yaml
- controllers/testdata/results/case_0/apiserver/deployment.yaml
- controllers/testdata/results/case_2/apiserver/deployment.yaml
- controllers/testdata/results/case_3/apiserver/deployment.yaml
This change introduces the option for the CR submitter to enable/disable routes for the Apiserver. When the route is enabled, an oauth proxy container is added to the api server and a k8s route is created.
To ensure that all external traffic goes through the route, and all pod-to-pod communications to apiserver go through port 8888 (default), we use a k8s network policy to enforce this behavior.
By allowing pods to communicate to apiserver via port 8888, we can continue provisioning mlpipelines-ui alongside this feature, otherwise the ui would also need to go through oauth proxy.
If the CR submitter switches enableRoute from 'true' to 'false' then the operator will clean up the existing route on the cluster.
Locally and on OCP OSD with: …
> Add enable route functionality.

- tests/basictests/dsp-operator.sh
- tests/resources/dsp-operator/test-dspo-cr.yaml
E2E tests Cr update, also a quick syntax update to curl call.
Can't test locally, will need to merge and test via ci
> Add required fields to e2e cr.

- tests/resources/dsp-operator/test-pipeline-run.yaml
The current upstream image has a pipeline named the same, so we cannot use this for ci testing, we will get null.
> Rename test pipeline.

- tests/basictests/dsp-operator.sh
Because pods will be "running" even if they are not ready.
> Check for ready status for dspa api server pod.

- tests/basictests/dsp-operator.sh
Remove the debug statements for e2e tests
Remove the debug statements from e2e tests
as described on e2e tests docs
> Remove the debug statements for e2e tests

- config/samples/dspa_simple.yaml
Currently sample cr deploy in readme instructions won't work because we specify namespace here.
> Remove ns from sample deployment to make readme work.

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- controllers/config/defaults.go
- controllers/database.go
- controllers/dspipeline_controller.go
- controllers/dspipeline_controller_test.go
- controllers/dspipeline_params.go
- controllers/storage.go
- controllers/testdata/deploy/case_3/cr.yaml
- controllers/testdata/deploy/case_3/secret1.yaml
- controllers/testdata/deploy/case_3/secret2.yaml
- controllers/testdata/results/case_0/apiserver/deployment.yaml
- controllers/testdata/results/case_0/mariadb/deployment.yaml
- controllers/testdata/results/case_2/apiserver/deployment.yaml
- controllers/testdata/results/case_2/mariadb/deployment.yaml
- controllers/testdata/results/case_3/apiserver/deployment.yaml
- controllers/testdata/results/case_3/database/secret.yaml
- controllers/testdata/results/case_3/storage/secret.yaml
- controllers/testutil/util.go
This change will fix external secret configuration, such that when a secret is provided for external db/storage, the appropriate internal DSPO managed secrets are created.
Summary of changes: 
* Made externaldb fields required 
* made db secret non mariadb specific (to account for externaldb)
* allow deployment of storage/db secrets for external options 
* disable minio deployment by default 
* add tests 
Deploy dspo from this image: quay.io/opendatahub/data-science-pipelines-operator:pr-51
`make install && make deploy IMG=quay.io/opendatahub/data-science-pipelines-operator:pr-51` on this branch.
Tested with external mariadb/minio on ocp live.
Create your external mariadb/minio db deployments using this tool: https://github.com/HumairAK/dspo-external-connection-devenv 
Follow readme, it …
> Correct secret generation for external secrets.

- Makefile
- config/base/kustomization.yaml
- config/base/params.env
- config/base/params.yaml
- config/manager/manager.yaml
- config/overlays/make-deploy/img_patch.yaml
- config/overlays/make-deploy/kustomization.yaml
This will allow us to sub in PR images during ci testing into kfdefs.
Build the following kfdef: 
```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: ds-pipelines-operator
namespace: odh-applications
spec:
applications:
- kustomizeConfig:
parameters:
- name: IMAGES_DSPO
value: quay.io/opendatahub/data-science-pipelines-operator:blah
repoRef:
name: manifests
path: config/
name: data-science-pipelines-operator
repos:
- name: manifests
uri: https://github.com/HumairAK/data-science-pipelines-operator/tarball/parameterize-image
version: master
```
`kfctl build -f above_file.yaml` then do a `kustomize build...` on the resulting `kustomize` folder.
> Add ability to parmaterize dspo image via kfdef.

- tests/scripts/install.sh
- tests/setup/kfctl_openshift.yaml
Patch pull request image for e2e tests
This would allow e2e tests to patch the image of dspo controller with the image of PR build image.
Depends-On: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/60
This is not tested, as pr tests need to be done on PR itself.
> Patch pull request image for e2e tests

- tests/scripts/install.sh
Fix the sed termination for a patch of images
The sed termination is required for a proper patch of the image.
Related-to: #61 
Ran sed operation on the kfdef
`sed -i "s#value: quay.io/opendatahub/data-science-pipelines-operator:latest#value: $IMAGE_TAG#" tests/setup/kfctl_openshift.yaml`
> Fix the sed termination for patch of images

- tests/basictests/dsp-operator.sh
Match the change with odh-manifests tests for consistency
With this PR,
the controller pods are explicitly checked, as in odh-manifests there multiple components installed and it cant be assumed only DSPO is installed on the namespace.
To have consistency we are including the same changes here.
https://github.com/opendatahub-io/odh-manifests/blob/master/tests/basictests/dsp-operator.sh
Already tested in odh-manifests.
```
cd tests
make build
make run
```
> Match the change with odh-manifests tests for consistency

- Makefile
fixing kubectl apply command that appears to be accidentally commented-out
run `make deploy OPERATOR_NS=odh-applications` and verify operator is actually deployed via `oc get po -n odh-applications`
> Fix commented-out command in Makefile deploy func

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
add kubebuilder validation markers for DSPA. There's currently only one field that's validate-able via simple markers.
Deploy to a cluster and try to set something not in the enum, and it works as expected
> add kubebuilder validation markers for DSPA

- config/crd/external/monitoring.coreos.com_servicemonitors.yaml
- config/internal/apiserver/monitor.yaml.tmpl
- config/internal/common/policy.yaml.tmpl
- config/rbac/role.yaml
- controllers/apiserver.go
- controllers/dspipeline_controller.go
Adding a Service Monitor template to procure DSP Application metrics
Also added a CRD for ServiceMonitor because the unit tests run in a fake local K8s cluster which doesn't have the `monitoring.coreos.com/v1` APIVersion.
Ran `make deploy` with these changes
Created a DSP Application in a separate namespace. 
Checked if a ServiceMonitor named `ds-pipelines-samples` came up.
Checked that specifically Data Science Pipelines Application metrics were scraped.
Metrics were found to be scraped by Prometheus:
> Adding a DSPA ServiceMonitor template

- controllers/dspipeline_controller.go
Some cleanup, removes redundant if statements and unused function parameters.
Unit/Integration tests should be sufficient for this, as there's no change to logic.
> Remove redundant/unused code.

- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
Make sure user has same access via cli and UI
Without the openshift-SAR, a user with access to the cluster can access the Routes
with the openshift-sar check in place, user needs to have access of the route in an rbac, to access the routes.
Deploy the PR on the cluster.
Trying access with user with zero permission , the UI and via the curl command,
both would have same behaviour
> Make sure user has same access via cli and UI

- config/manager/manager-service.yaml
- config/prometheus/monitor.yaml
Rename the component to respect name-prefix
The nameprefix, is added to each component list in kustomize
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/79745047878305b07648066c78696ac9878f89d0/config/base/kustomization.yaml#L4
the name of service and servicemonitor, were showing repetition.
ex: `data-science-pipelines-operator-data-science-pipelines-operator-monitor`
`kustomize build config/base`
> Rename the component to respect name-prefix

- config/manager/manager-service.yaml
- config/manager/manager.yaml
If we do an `oc get pods -l app.kubernetes.io/created-by=data-science-pipelines-operator` after deploying DSP Operator, it won't return any pods, because only the DSPO deployment contains this label, the pods don't. Adding this label to the pods as well, so they could be filtered using the component name, that is, Data Science Pipelines Operator.
- Deploy a DSP Operator instance.
- Try out  `oc get pods -l app.kubernetes.io/created-by=data-science-pipelines-operator` in the same namespace where the operator is deployed. Make sure it displays DSPO pods.
> Add a data-science-pipelines-operator label for DSPO manifests

- .github/workflows/pr-close-image-delete.yml
Github action: Direct authenticate the skopeo function
As the login method was giving trouble, directly trying to authenticate via function.
Tested on the fork repo.
https://github.com/harshad16/data-science-pipelines-operator/actions/runs/4612496076/jobs/8153461080
> Github action: Direct authenticate the skopeo function

- config/internal/apiserver/role_ds-pipeline.yaml.tmpl
- tests/basictests/dsp-operator.sh
Update e2e CI tests to utilize the API route rather than UI (which will eventually not exist)
Update urls used in the e2e CI tests to use APIServer route
Testing: Verify CI Passes (it's literally what we're updating ;) )
> Update e2e basictests to use APIServer Route

- config/samples/dspa_all_fields.yaml
- controllers/config/defaults.go
- controllers/dspipeline_controller.go
- tests/basictests/dsp-operator.sh
- tests/scripts/installandtest.sh
This PR will introduce DataSciencePipelinesApplication CR Status fields.
Data Science Pipelines is not an operator that deploys DSP stacks in multiple namespaces. In order to get a complete observation of the stack health, conditions must be implemented.
In this implementation, the following conditions were implemented:
* DatabaseReady
* ObjectStorageReady
* ApiServerReady
* PersistenceAgentReady
* ScheduledWorkflowReady
* UserInterfaceReady
* Ready
Each of these conditions check if the `Available` Deployment condition to verify if the component is ready to use. The last condition is a general condition based on the previous conditions and the way the user created the DSP stack (with external resources or without the UI)
Simply follow the instructions in the readme provided to deploy and …
> Create DSPA Status Condition fields

- README.md
We need to specify supported tekton sdk version for the DSPA instance. We also need to provide a workaround for users on an unsecured OCP/K8s cluster.
Tested instruction against live deployment
> Clarify readme.

- config/base/params.env
- config/manager/manager.yaml
- tests/basictests/dsp-operator.sh
We want to use resource requests no more than what's needed.
Via `make deploy`, deployed dspa and worked without issues. Will need perf testing post merge to adjust further if needed.
> lower resource requests 

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/deployment.yaml.tmpl
- config/internal/apiserver/sample-config.yaml.tmpl
- config/internal/apiserver/sample-pipeline.yaml.tmpl
- controllers/apiserver.go
- controllers/dspipeline_controller_test.go
- controllers/testdata/deploy/case_2/cr.yaml
- controllers/testdata/deploy/case_3/cr.yaml
- controllers/testdata/results/case_0/apiserver/deployment.yaml
- controllers/testdata/results/case_2/apiserver/deployment.yaml
- controllers/testdata/results/case_3/apiserver/sample-config.yaml
- controllers/testdata/results/case_3/apiserver/sample-pipeline.yaml
Allows us to override the default pipeline, in this case with a more data-science applicable example
Introduce the sample-config and sample-pipeline ConfigMaps, which are mounted as volumes on the APIServer pod.  these contain overrides for `sampel_config.json` and a compiled  Tekton pipeline showing a simple Iris training run example.  This shouldn't be merged before the matching (DSP PR)[https://github.com/opendatahub-io/data-science-pipelines/pull/80] which provides the py source code to the pipeline (else there will be a dead link in the sample pipeline description
Built a dev image of the DSPO, which can be used to override the image defined in the controller-manager Deployment in odh-applications.  From there, create a new DSPA using the dspa_simple.yaml definition and verify …
> Add/Enable Customizable Sample Pipeline to APIServer

- README.md
- controllers/dspipeline_controller.go
- controllers/metrics.go
- go.mod
- main.go
Add prometheus metrics for the DSPA Status Fields
Exposes Prometheus GaugeVecs for each CR Status field, such that we can monitor states and alert accordingly
To test: 
1. build DSPO image and deploy
2. Create a DSPA
3. Go to prometheus and verify/explore new `dspa_*` metrics
> Add CR Ready Status Metrics

- controllers/apiserver.go
- controllers/common.go
- controllers/database.go
- controllers/dspipeline_controller.go
- controllers/mlpipeline_ui.go
- controllers/persistence_agent.go
- controllers/scheduled_workflow.go
- controllers/storage.go
- controllers/viewer_crd.go
Log messages now includes the namespace and DSPA name that is being reconciled.
* Run `make podman-build podman-push IMG=quay.io/{USERNAME}/dspo`
* Run `make deploy IMG=quay.io/{USERNAME}/dspo`
* Create a DSPA
* Check if log linges shows namespace and DSPA name
> Add namespace and DSPA name in Reconciler logs

- .github/workflows/tag-release-quay.yml
- currently any forked repo will be triggered by new tag and failure
When I created new [tag](https://github.com/red-hat-data-services/data-science-pipelines-operator/releases/tag/v1.25.0-rhods) in downstream RHODS repo, I got failed run https://github.com/red-hat-data-services/data-science-pipelines-operator/actions/runs/4783277428
- the reason is it does not have quay auth
- but we should not need this run at all
This PR is only adding an extra check to see if the repo is from opendatahub-io or not 
It prevents any forked repo to start workflow by any new tag
- Manually created a tag named "test-tag" locally
- Push to my forked github repo, see https://github.com/zdtsw/data-science-pipelines-operator/tags
- No Action was started, see …
> Fix: only enable tag-release-quay workflow for upstream opendatahub-io

- README.md
- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/samples/external-object-storage/dspa_simple.yaml
- config/samples/external-object-storage/kustomization.yaml
- config/samples/external-object-storage/storage-creds.yaml
- controllers/config/defaults.go
- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/storage_secret.yaml
For cloud storage like aws s3, the secure port is 443, but this does not work with the minio module that is used by dsp api server, so instead in such a case we make port optional, and do not require it. When an empty port is provided, then it is simply not used by dsp api server.
Test cases are provided to reflect this change.
Docs have also been provided on how to utilize this external object storage with an aws s3 specific example usecase.
Locally and in cluster.
> Make object store port/secure scheme optional.

- config/internal/scheduled-workflow/role.yaml.tmpl
Recurring runs are not creating pipeline runs after triggered. Scheduled Workflow pod is returning the following error:
```
Error creating workflow in namespace (kverlaen-dsp): pipelineruns.tekton.dev "runofdemoiris-training06a9wjmp-1-3349978302" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>: &{TypeMeta:{Kind:Workflow APIVersion:tekton.dev/v1beta1} ObjectMeta:{Name:runofdemoiris-training06a9wjmp-1-3349978302 GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[pipeline/runid:c79c0e77-321a-43db-aa36-e3fcc199f741 scheduledworkflows.kubeflow.org/isOwnedByScheduledWorkflow:true …
```
> Fix Scheduled Workflow role to allow create runs

- config/internal/apiserver/artifact_script.yaml.tmpl
- controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_3/expected/not_created/configmap_artifact_script.yaml
Due to a bug in upstream code, scheduled run pipelines are not getting the k8s annotations on the tekton pods that contain the artifact endpoint and bucket info. As such artifact passing works in regular (non-scheduled) runs but not for recurring runs, failing at the copy-artifacts container step.
Hardcoding these values within the artifact script serves as a sufficient work around for this problem.
On an ocp cluster running in osia.
Instructions 
`make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-111"`
Then create a recurring run and confirm it finishes to completion successfully, the run should utilize artifact passing (for example flip-coin example). Confirm by checking bucket for artifacts, and the container "step-copy-artifacts".
Also confirm regular runs remain …
> Fix artifact passing for recurring runs.

- config/internal/apiserver/role_ds-pipeline-user-access.yaml.tmpl
- controllers/apiserver.go
Adding a role for the DSP end user to utlize for long term programmatic access.
- Deploy DSPO and create a DSPA instance
- Create a ServiceAccount in a different namespace. Here's an example:
```
kind: ServiceAccount
apiVersion: v1
metadata:
name: test-dsp-service-account
namespace: test-dspa-sa
```
- Create a RoleBinding that binds the role defined in this PR, in the same namespace as the DSPA instance. Reference the SA in this RoleBinding. Here's a sample RoleBinding that can be applied:
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: ds-pipeline-user-access-sample
namespace: <same-namespace-as-DSP-instance>
subjects:
- kind: ServiceAccount
name: test-dsp-service-account
namespace: test-dspa-sa
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: …
```
> Add a role for Data Science Pipelines end user

- config/manager/manager-service.yaml
- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
Update DSP Operator labels to be more specific to DSP/DSPO. Closes [RHODS-7918](https://issues.redhat.com/browse/RHODS-7918)
Deployed a DSPO instance, checked that the deployment, service, service monitor, roles came up correctly.
Checked that the metrics are listed out in the `Observe` section of the OpenShift console:
> Update DSP Operator labels

- controllers/metrics.go
Updates Readiness metrics to use `dspa_namespace` as `namespace` is overwritten/overrided
Updates Readiness metrics to use `dspa_namespace` as `namespace` is overwritten/overrided
- Deploy DSPO (you can use quay.io/gm frasca/data-science-pipelines-operator:ready-status-metrics-0.1.1)
- Look at metrics via ODH Dashboard
- Verify data_science_pipelines_application_XXXXX_ready metrics now have `dspa_namespace` label
> Update Ready Metrics Labels to use dspa_namespace

- controllers/dspipeline_controller.go
Must retrieve DSPA state before calling Update() in reconciler
Add a Get() object fetch immediately before Update() call is made in the DSPA Status update procedure.  This will guarantee CR is in latest state, which is what was causing the error (but only once, since future loops *would* probably have the latest status)
1. Build and deploy DSPO (testing image: quay.io/gmfrasca/data-science-pipelines-operator:reconcile-bugfix-0.0.1)
2. Tail the DSPO log (oc logs -n $DSPO_NAMESPACE -f $DSPO_POD_NAME)
3. In a seperate terminal, create a DSPA
4. Wait for DSPA to fully come up
5. Delete a pod to cause DSPA status to change (persistenceagent or scheduledworkflow are good for this)
6. Make sure no Reconciler Error appears in the DSPO log
> Bugfix: Benign modified DSPA object error

- config/base/kustomization.yaml
- config/base/params.env
- config/configmaps/files/config.yaml
- config/internal/apiserver/deployment.yaml.tmpl
- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- config/manager/manager.yaml
- controllers/config/defaults.go
- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_0/config.yaml
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_1/config.yaml
- controllers/testdata/declarative/case_2/config.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_3/config.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- kfdef/kfdef.yaml
Parameterize the oauth-proxy image as config var
Move the oauth-proxy image to configmap , so it can assigned value directly.
Use the below image for the deployment
Image: `quay.io/opendatahub/data-science-pipelines-operator:pr-120`
replace the value here:https://github.com/opendatahub-io/data-science-pipelines-operator/blob/fe12ad963f0c7f498c941f364ffccbe0985b53c0/config/base/params.env#L8
deploy the operator and check the yaml for testing.
> Parameterize the oauth-proxy image as config var

- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_4/config.yaml
- controllers/testdata/declarative/case_4/deploy/00_cr.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_4/expected/created/mariadb_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/minio_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/persistence-agent_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/scheduled-workflow_deployment.yaml
- controllers/testutil/equalities.go
Fixes #67 
If the `image` field is specified in a DSPA CR, it should take precedence over the image defaults provided in the DSPO config.
Changes DSPAParams behavior to only set the XXXX.Image component if it is not specified in the DSPA CR
- Deploy operator built from PR.
- Create DSPA from stardard dspa simple, verify 'normal' images used
- Create DSPA with `image` field specified for APIServer, PersistenceAgent, ScheduledWorkflow, and UI.  Also set ArtifactImage, CacheImage, and MoveResultImage in apiServer spec.  These can be fake values.  Verify the specified images have overrident the ones used from first DSPA
> Bugfix: Images Specified in DSPA CRs should override DSPO defaults

- tests/basictests/dsp-operator.sh
Add an e2e test case for DSPO Service Monitor and metrics. Closes [RHODS-8312.](https://issues.redhat.com/browse/RHODS-8312)
- Deploy a DSPA instance
- Run the following commands:
- `make build` -- to create the test container image
-  `make run TESTS_REGEX=ml-pipelines`
-  This will run the container image locally
-  It will further apply the kfdef defined in the `kfctl_openshift.yaml` file.
- If you have the kfdef installed already, you can run this instead:
`make run SKIP_INSTALL=true SKIP_KFDEF_INSTALL=true`
> Add a check for DSPO Service Monitor and metrics

- config/base/params.env
I noticed when deploying DSPO by pointing a kfdef at this repository, I get a month-old version of DSPO. When I do the same for dashboard, I get main. We might as well default to main too ... if someone is pointing at DSPO or building it from source, they probably want bleeding edge anyway.
I didn't test it yet.
> default to deploying dspo's main tag

- config/internal/apiserver/deployment.yaml.tmpl
- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
Places sidecar containers (namely, oauth proxy) after the main container for easier debugging
Reorder the container specs for APIServer and UI such that the OAuth Proxy container is listed *after* the main container of the pod
1.  Deploy DSPO and a DSPA using PR codebase (`go run main.go --config pathtoconfigdir/`).  Verify APIServer and UI Deployments now list their respective main pods before AuthProxy in the Deployment definition yaml
2. As an additional verify, run `oc rsh ds-pipelines-{{DSPANAME}}` (without specifying the container via `-c`) and verify the pod accessed is the APIServer, not OAuthProxy
> Reorder Multi-container Deployments to use main container first

- config/rbac/role.yaml
- controllers/dspipeline_controller.go
Add RBAC rules for mcad and ray roles
Deployed a DSPO and a DSPA instance, made sure that all DSPA components come up as expected, and not just minio/mariaDB.
> Add RBAC rules for mcad and ray roles

- config/internal/common/mlmd-envoy-dashboard-access-policy.yaml.tmpl
- config/internal/common/policy.yaml.tmpl
- controllers/common.go
Adding MLMD components to the DSPA Network Policy, and provide ODH dashboard access to the metadata envoy service. Closes https://github.com/opendatahub-io/data-science-pipelines-operator/issues/160
- Deployed a DSPO and DSPA instance with these updates
- Deployed an ODH dashboard instance by applying the ODH core kfdef in the same namespace where DSPO was deployed.
- Ensured that the MLMD components were up, metadata envoy service was running.
- curled to the envoy service from the dashboard pod.
`$ curl ds-pipeline-metadata-envoy-sample.test-dspa-3.svc.cluster.local:9090
upstream connect error or disconnect/reset before headers. reset reason: remote reset`
Dashboard was able to reach the envoy service.
> Add MLMD components to Network Policy

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- controllers/dspipeline_params.go
- controllers/util/util.go
Infer the "secure" field in dspa based on the scheme which resolves #157 
Manually tested this on Openshift Cluster to ensure removing this field doesn't hinder anything.
> Infer the "secure" field in dspa based on scheme

- .github/workflows/gh-to-jira.yaml
Resolves: https://github.com/red-hat-data-services/data-science-pipelines-operator/issues/44
Related: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/177
Workflow to provide support for downtream jira support.
Collects all prs given a label filter set between the tag range provided for each repos, and submits to the designated jira project.
Tested from my fork to a playground jira instance.
> Add gh to jira action.

- config/internal/apiserver/artifact_script.yaml.tmpl
- controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Resolves:  https://github.com/opendatahub-io/data-science-pipelines-operator/issues/214
The workaround identifies artifacts in workspace and pushes them to s3 storage.
On live ocp cluster. Run pipeline and confirm artifacts are stored in s3 when doing data passing, or save to output path.
> Add push artifact work around.

- Dockerfile
Related https://github.com/opendatahub-io/data-science-pipelines-operator/issues/177
changing the go-toolset to use the registry that doesn't require authentication same as for the ubi image further down the dockerfile.
none needed, the images are identical.
> Use unauthenticated images for go-toolset.

- .github/actions/build/action.yaml
- .github/workflows/tag-and-build.yml
Furthers #177
This change makes it so we ensure we don't over-write existing tags, and also converts the build logic into a re-usable action.
No need to test, you can see it in action here: https://github.com/HumairAK/data-science-pipelines-operator/actions/runs/5716850525 see the attempts, it fails when the tag is present, and succeeds when it is not. Quay reports on all deleted tags as well so we need to verify if these tags are indeed deleted by inspecting their "end time stamp", if they have one it means it's deleted. Furthermore, we don't use `podman image exists` because this will require us to pull the image, this solution instead just queries quay directly and does some `yq` parsing to verify existence of tags.
> Tag build image exists

- controllers/dspipeline_controller.go
Added RequeueAfter which periodically reconciles and fixes #173
Manually tested this by ->
1. Created a DSPA referring to a secret that doesn't exist.
2. Create the secret in question.
3. Monitor the DSPO logs and see that it reconciles and gets DSPA up and running as it should.
> Added RequeueAfter to ensure periodic reconciliation

- .github/workflows/build-prs-trigger.yaml
- .github/workflows/build-prs.yml
Related #https://github.com/opendatahub-io/data-science-pipelines-operator/pull/243
GH does not allow PR workflows to access secrets (for obvious reasons). This pr proposes a secure way to execute pr image builds in an unprivileged environment. Workflows triggered via `workflow_run` event are always triggered from default branch, as such can access repository tickets. 
Tested with a fork pr [here](https://github.com/HumairAK/data-science-pipelines-operator/pull/6). 
Triggered workflow when pr closed:  [1](https://github.com/HumairAK/data-science-pipelines-operator/actions/runs/5754669055/job/15600458922)
Triggered work when pr opened: [2](https://github.com/HumairAK/data-science-pipelines-operator/actions/runs/5754626535)
> Add secure pr build triggers.

- config/internal/mariadb/deployment.yaml.tmpl
- config/internal/mariadb/mariadb-sa.yaml.tmpl
- config/internal/minio/deployment.yaml.tmpl
- config/internal/minio/minio-sa.yaml.tmpl
- controllers/database.go
- controllers/storage.go
Resolves #204 
Deploy DSPO and DSPA.
Port forward to the mariaDB port:
```
POD_NAME=$(oc get pods -l app=mariadb-sample -o=jsonpath='{.items[0].metadata.name}')
(base) 
oc port-forward ${POD_NAME} 3306:3306
```
Connect to the port, login inyo mysql
```
mysql -h 127.0.0.1 -P 3306 -u root
```
login into MariaDB
```
mariadb-install-db --user=mysql
```
Make sure you're able to connect successfully.
> Add non-default SAs to MariaDB and Minio

- .github/workflows/odh-manifests-PR-sync.yml
Resolves #178 
Updating the workflow to create a sync PR into odh-manifests, to have the dsp-developers' fork cloned instead of opendatahub-io/odh-manifests.
> Fix GH workflow to clone dsp-developers/odh-manifests fork

- .github/workflows/odh-manifests-PR-sync.yml
Resolves #178 
- Updated input descriptions to add examples
- Updated branch and tag fields to use input variables
- Updated repository to create the PR to be `opendatahub/odh-manifests`
> Fixing GH workflow repo name and updating input descriptions

- .github/workflows/odh-manifests-PR-sync.yml
This change adds some additional env vars, and corrects the location where the PR is sent (odh/odh-manifests).
Rsync is also switched to using checksums, mod-time in the gh action did not appear to be idempotent.
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/178
See example run in a test org [here](https://github.com/example-test-organization/data-science-pipelines-operator/actions/runs/5825954703/job/15798784447), with resulting pr [here](https://github.com/example-test-organization/odh-manifests/pull/5). The example run simulates a release situation where odh-manifest is caught up to 1.2.x b ranch, and we want to forward some changes from [1.3.x](https://github.com/example-test-organization/data-science-pipelines-operator/tree/v1.3.x) to odh-manifest.
> Correct remote location for manifest sync action.

- controllers/storage.go
- controllers/suite_test.go
- Provided Credentials may not necessarily have ListBucket permissions, so update the Object Store Health Check to use StatObject instead
Resolves #262 
Updates DSPA ObjectStore prereq Health Check to use StatObject instead of ListBuckets.  We cannot assume that the provided credentials have ListBuckets permissions granted, so updating the verification command to StatObject (which is used as part of GetObject/ReadObject and required for the underlying DataSciencePipelines functionality)
Attempt to create a DSPA with externalStorage, and use credentials that only have PutObject, GetObject, and DeleteObject permissions.  Ensure that the DSPA eventually passes the health check (ObjectStorageAvailable CR condition = `true`).  Additional test cases include using default objectStorage and …
> Update ObjectStore HealthCheck to use StatObject

- Makefile
- controllers/apiserver_test.go
- controllers/common_test.go
- controllers/database_test.go
- controllers/dspipeline_controller_func_test.go
- controllers/dspipeline_fake_controller.go
- controllers/dspipeline_params.go
- controllers/mlmd_test.go
- controllers/mlpipeline_ui_test.go
- controllers/persistence_agent_test.go
- controllers/scheduled_workflow_test.go
- controllers/storage_test.go
- controllers/suite_test.go
- controllers/testutil/util.go
- go.mod
Resolves #162
- Implements the concept of 'unit' and 'func' test classes
- Adds 2 new Make commands: `make functest` and `make unittest`, which run their respective classes of tests using build labels denoted below
- `make test` still runs both unit and functional tests.
- Updates suite_test.go to run as a functional-class test suite (apply build label `test_functional`)
- Add unit tests for all sub-reconciliation functions (build label `test_unit`)
- run `make test`, ensure all passing
- run `make functest`, ensure passes
- run `make unittest`, ensure passes and >20% code coverage (specified as minimum target in issue spec)
> Add Unit Tests

- config/internal/apiserver/artifact_script.yaml.tmpl
Resolves #294 
Note that this resolves only the failing pods (i.e. scheduled runs will complete successfully). 
However big data passing still does not work, i.e. data doesn't get stored in s3, this is due to https://github.com/opendatahub-io/data-science-pipelines-operator/issues/300, which is larger in scope and requires further attention.
As pointed out in #294 the env vars `ARTIFACT_ENDPOINT` and `ARTIFACT_BUCKET` are not being populated because the tekton annotations with the obj store details are not being added in scheduled runs, this will hard code those fields to allow for data passing to work.
1. Deploy dspo/dspa
2. Create a scheduled run that does data passing (e.g. iris example)
3. Confirm data shows up in s3
4. Also run flip-coin scheduled run, confirm it works without issues …
> Hardcode obj store info in artifact script.

- .gitignore
- docs/example_pipelines/condition.py
- docs/example_pipelines/condition.yaml
Some tasks and especially root task in pipeline uses: `quay.io/hukhan/python:alpine3.6`
see:
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/b34fbb8402efd3f2092c7931f683d5b906809961/docs/example_pipelines/condition.yaml#L84
other steps used (dockerhub):
`image: python:alpine3.6`
see:
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/b34fbb8402efd3f2092c7931f683d5b906809961/docs/example_pipelines/condition.yaml#L455
so this changes aligns images _from all tasks, to root task image_.
Might incur in pipeline failure "in the middle" as the tasks using different image might incur in backoff etc.
Example as I followed the quickstart in: https://github.com/opendatahub-io/data-science-pipelines-operator#quickstart
Pipeline definition file as coming in …
> align example pipeline yaml images

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Resolves #207
CRD validation now takes into account the regexes used to validate identifiers for mariadb user/db names
1. deploy dspo
2. deploy dspa with invalid user/db names for mariadb spec, example: 
```yaml
spec:
database:
mariaDB:
pipelineDBName: test-fail
username: test-fail
```
3. you should see an error reported from api server
4. deploy with valid pipeline db and user names, it should now work
```yaml
spec:
database:
mariaDB:
pipelineDBName: test_pass
username: test_pass
```
5. Try different combinations
**NOTE**:  that if a user had deployed a DSPA with invalid db identifier names (e.g: "test-fail"), then updated DSPO, DSPO will report errors for this DSPA until the offending DSPA invalid field is updated or removed, example: 
``` …
```
> Add pattern requirement for mariadb db/user name.

- .github/actions/kind/action.yml
- .github/resources/crds/buildconfig-crd.yaml
- .github/resources/crds/deploymentconfig-crd.yaml
- .github/resources/crds/imagestream-crd.yaml
- .github/resources/crds/servicemonitor-crd.yaml
- .github/resources/kfdef/kfdef.yaml
- .github/resources/kind/kind.yaml
- .github/resources/olm/catalogsource.yaml
- .github/resources/olm/operatorgroup.yaml
- .github/resources/olm/subscription.yaml
- .github/workflows/upgrade-test.yml
- tests/upgrades/main.sh
Resolves #216 
- This GH workflow sets up a kind cluster, installs OLM, deploys the OpenDataHub operator, deploys DSPO using a KfDef pointing to the most recently released branch specified via the GH action input. It further spins up a DSPA instance.
- The action upgrades DSPO to point to a candidate version, specified in the action input, and spins up a DSPA instance in a separate namespace.
- For now, we've set the most recently released branch to be an input just to be able to run and test this workflow out once merged, but we'll eventually set it to be the `main` branch of `opendatahub/data-science-pipelines-operator` repository in the KfDef.
- Specific upgrade testing checks to ensure that the upgrade went smoothly will be covered in a separate PR.
Find a successful workflow run on …
> Add Upgrade testing workflow

- controllers/config/defaults.go
- controllers/database.go
- controllers/dspipeline_controller.go
- controllers/storage.go
Resolves #280
May also address #260 -- not confirmed.
Add 1second time out to db/storage healthcheck.
Also add concurrent reconciles so when deploying multiple DSPAs they do not get backlogged (as much) in watcher queue.
1. Deploy DSPO from this pr
2. Deploy 3 dspa's simultaneously 
3. Ensure that the status field is updated in ~1seconds for all 3 (confirm 1s timeout on db/storage health check) 
4. Also ensure that pods start spinning up at the same time for all 3 (confirm concurrent reconciles)
5. Regression checks:
* Ensure when db/s3 info is invalid the status is reported as such in the dspa CR status field 
* Ensure valid external db/s3 configurations result in full DSPA deployment (run a flip coin to sanity check)
* Ensure valid external s3 + default mariadb results in full dSPA …
> Add timeout to db/storage health checks, increase reconcile concurrency 

- .github/workflows/upgrade-test.yml
Resolves #216 
Updating the replace statement in the step to prepare kfdef for upgrade testing, to correctly replace versions. Currently, it attempts to replace `main` with the `candidate` version, but since the kfdef's already been updated to replace `main` with the `released` version, the kfdef update doesn't happen. Check this run on my fork for instance: https://github.com/DharmitD/data-science-pipelines-operator/actions/runs/6164537886/job/16730453973
If you look at the printed kfdef contents, the uri still points to `1.2.x` which I've subbed in as the released branch in the workflow inputs.
This fix would replace `released` version with the `candidate` version in the kfdef. Example run of this fix on my fork: https://github.com/DharmitD/data-science-pipelines-operator/actions/runs/61 …
> Update kfdef to correctly replace versions

- controllers/testutil/equalities.go
- go.mod
- go.sum
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/318
Improved logs for deep comparisons in `equalities.go`. With these changes, deep comparison errors will look like:
```shell
selector is not equal:
MatchLabels.map[dspa]: whaaaat? != testdsp0
MatchLabels.map[app]: weird value != ds-pipeline-testdsp0
MatchLabels.map[component]: another weird value != data-science-pipelines
```
Change any of the expected CRs in https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main/controllers/testdata/declarative and check the failures.
> Improved logs for deep comparisons in equalities.go

- config/base/kustomization.yaml
- config/base/params.env
- config/manager/manager.yaml
- controllers/dspipeline_controller.go
- main.go
Resolves #368
Added a new argument "MaxConcurrentReconciles" in the manager.yaml file and read the value from the argument to use it in the controller.
Pull my branch and once you deploy it, we should be able to see the worker count in the logs as below:
Starting workers	{"controller": "datasciencepipelinesapplication", "controllerGroup": "datasciencepipelinesapplications.opendatahub.io", "controllerKind": "DataSciencePipelinesApplication", "worker count": 10}
If you want to update the count, update "MaxConcurrentReconciles" arg in manager.yaml file and redeploy to see the updated count in logs. 
If you want to see the usage of "DefaultMaxConcurrentReconciles"  which is set to 10, remove the "MaxConcurrentReconciles" arg in manager.yaml file and redeploy to see the worker count …
> Parameterize DSPO max concurrency count

- config/v2/exithandler/clusterrole.leaderelection.yaml
- config/v2/kfptask/clusterrole.leaderelection.yaml
- config/v2/pipelineloop/clusterrole.leaderelection.yaml
Fixes names for leader election clusterroles (missing -clusterrole suffix) 
`make v2deploy` and ensure leader election clusterroles properly map to their appropriate clusterrolebindings
> Fix Leader Election Cluster Role Names

- config/internal/apiserver/default/deployment.yaml.tmpl
- config/v2/exithandler/webhook/clusterrole.clusteraccess.yaml
- config/v2/kfptask/webhook/clusterrole.clusteraccess.yaml
- config/v2/pipelineloop/webhook/clusterrole.clusteraccess.yaml
- controllers/apiserver_test.go
- controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
Resolves #379 
- Add MLMD GRPC Env Vars to APIServer if Defined
- Update RBAC for webhook clusterroles:
- Allow capability to delete mutating and validating webhook configurations CRs
- Allow capability to CRUD finalizers on openshift-pipelines namespace
Deploy v2 infra (`make v2deploy`), ensure webhooks do not have Permission Denied errors
Deploy DSPA with MLMD, ensure METADATA_GRPC_SERVICE_SERVICE_HOST and METADATA_GRPC_SERVICE_SERVICE_PORT are defined in the APIServer Deployment Environment Vars
> Webhook RBAC and APIServer EnvVar updates

- .github/workflows/nightly_tests.yml
Resolves #372
Add a simple GH Workflow that runs Nightly.  To start we simply run a sample build and execute unit and functional tests. 
Verify logs from https://github.com/gmfrasca/data-science-pipelines-operator/actions/workflows/nightly_tests.yml looks good.  Depending on permissions you may be able to run it manually yourself as well (this is the reason for `workflow_dispatch: {}` in the triggers)
> Add Nightly Build/Test GHAction stub

- config/internal/common/default/policy.yaml.tmpl
Add NetworkPolicy for kfp-driver and TaskRuns to allow access to AP Server
Resolves #369
`kfp-driver` is located under `openshift-pipelines` namespace, and it needs access to DSP API Server. On the DSP namespace, TaskRun pods also need access to API Server.
The NetworkPolicy changes are made to satisfy the new v2 requirements
* Deploy DSPOv2
* Create a DSPA CR under a specific namespace
* Use the [iris-pipeline example](https://gist.github.com/rimolive/a53200ddfc85ef4972813437e5acad59) to create and run a pipeline
* The pipeline run should finish successfuly
> DSPv2 NetworkPolicy changes

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/default/deployment.yaml.tmpl
- config/internal/common/default/policy.yaml.tmpl
- config/v2/driver/deployment.yaml
- config/v2/exithandler/clusterrole.leaderelection.yaml
- config/v2/pipelineloop/controller/deployment.yaml
- config/v2/pipelineloop/webhook/deployment.yaml
- config/v2/tektoncrds/kustomization.yaml
- controllers/dspipeline_params.go
- controllers/mlmd.go
- controllers/mlmd_test.go
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
Resolves [#369 ](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/369)
Resolves [#380 ](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/380)
This PR contains the last round of required changes to have a functional Deployment of DSPv2 through the operator.
**NOTE:** For this test, it is important stick to the namespace names, specially the DSPA deployment. There are still tasks to do before having it to support multiple namespaces.
* Run the following commands to prepare the environment. **NOTE:** Make sure there are no other DSP installations in the testing cluster:
```
$ export IMAGE=quay.io/<QUAY_USERNAME>/dspo:v2
$ export DSPO_NS=data-science-pipelines-operator-v2
$ export DSPA_NS=data-science-pipelines-application-v2
$ oc new-project …
```
> Last changes for DSPv2 PoC

- config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_2/expected/created/sample-pipeline.yaml.tmpl
- controllers/testdata/declarative/case_6/config.yaml
- controllers/testdata/declarative/case_6/deploy/cr.yaml
- controllers/testdata/declarative/case_6/expected/apiserver_deployment.yaml
- controllers/testdata/declarative/case_6/expected/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_6/expected/mariadb_deployment.yaml
- controllers/testdata/declarative/case_6/expected/minio_deployment.yaml
- controllers/testdata/declarative/case_6/expected/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_6/expected/persistence-agent_deployment.yaml
- controllers/testdata/declarative/case_6/expected/sample-config.yaml.tmpl
- controllers/testdata/declarative/case_6/expected/sample-pipeline.yaml.tmpl
- controllers/testdata/declarative/case_6/expected/scheduled-workflow_deployment.yaml
Resolves #425 
This change will replace the sample iris-pipeline in DSPO to an IR version with artifacts included.
* Run the following commands to build and deploy the testing environment:
```
$ export QUAY_USERNAME=<replace with your quay.io username>
$ export IMAGE=quay.io/${QUAY_USERNAME}/dspo:v2.1 # Make sure you marked this image as public in your quay.io account
$ export OCP_PIPELINE_NS=openshift-pipelines
$ export DSPO_NS=data-science-pipelines-operator-v2
$ make podman-build podman-push IMG=$IMAGE # Make sure you ran "podman login" first
$ make v2deploy IMG=quay.io/rmartine/dspo:v2.1 V2INFRA_NS=$OCP_PIPELINE_NS OPERATOR_NS=$DSPO_NS
$ make deploy IMG=quay.io/rmartine/dspo:v2.1 V2INFRA_NS=$OCP_PIPELINE_NS OPERATOR_NS=$DSPO_NS
$ oc apply -f …
```
> Replace sample iris-dataset pipeline with a v2 one

- config/overlays/make-v2deploy/kustomization.yaml
- config/v2/configmaps/configartifactbucket.yaml
- config/v2/configmaps/configartifactpvc.yaml
- config/v2/configmaps/configdefaults.yaml
- config/v2/configmaps/configobservability.yaml
- config/v2/configmaps/configspire.yaml
- config/v2/configmaps/configtrustedsources.yaml
- config/v2/configmaps/featureflags.yaml
- config/v2/configmaps/kustomization.yaml
- config/v2/exithandler/webhook/kustomization.yaml
- config/v2/kfptask/webhook/kustomization.yaml
- config/v2/secrets/kfpexithandlerwebhookcertssecret.yaml
- config/v2/secrets/kfptaskwebhookcertssecret.yaml
- config/v2/secrets/kustomization.yaml
- config/v2/secrets/tektonpipelineloopwebhookcertssecret.yaml
Resolves #377 
Added missing Tekton ConfigMaps and Secrets. Also modified kustomization.yaml files to ensure that namePrefix is added to all the other files except for these specific ConfigMaps and Secrets.
1. Ensure the OCP Cluster you test on has OpenShift Pipelines Operator (v1.12.0+) installed.
2. Run `make v2deploy V2INFRA_NS=${OPERATOR_NS}` after setting OPERATOR_NS to the openshift-pipelines namespace.
3.  Ensure the specific ConfigMaps and Secrets are created as per screenshots below:
4. Ensure all the webhook pods are up and running without throwing any errors in the logs of missing the respective configmaps and secrets.
> Added missing Tekton ConfigMaps and Secrets.

- config/v2/cache/clusterrole.yaml
- config/v2/driver/clusterrole.yaml
- config/v2/exithandler/clusterrole.leaderelection.yaml
- config/v2/exithandler/controller/clusterrole.clusteraccess.yaml
- config/v2/exithandler/controller/clusterrole.tenantaccess.yaml
- config/v2/kfptask/clusterrole.leaderelection.yaml
- config/v2/kfptask/webhook/clusterrole.clusteraccess.yaml
- config/v2/pipelineloop/clusterrole.leaderelection.yaml
- config/v2/pipelineloop/controller/clusterrole.tenantaccess.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/354
Slimming down v2 ClusterRoles to a stricter spec, to help minimize our security footprint
PF details on the updates made as part of this PR, in this [doc.](https://docs.google.com/document/d/1PdtePscGG1P6KBNgUY0r0l5LvVKyI8zojoAmn9c06pw/edit?usp=sharing)
* Run the following commands to prepare the environment. **NOTE:** Make sure there are no other DSP installations in the testing cluster:
```
$ export IMAGE=quay.io/<QUAY_USERNAME>/dspo:v2
$ export DSPO_NS=data-science-pipelines-operator-v2
$ export DSPA_NS=data-science-pipelines-application-v2
$ oc new-project $DSPO_NS
$ oc new-project $DSPA_NS
$ make podman-build podman-push IMG=$IMAGE
$ make v2deploy IMG=$IMAGE V2INFRA_NS=openshift-pipelines
$ make …
```
> Slim down v2 ClusterRoles

- config/v2/driver/clusterrole.yaml
- config/v2/exithandler/controller/clusterrole.clusteraccess.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/354
While testing the updates made in https://github.com/opendatahub-io/data-science-pipelines-operator/pull/442, we realized that run creation fails and we would need to add permissions related to runs and tasks back in v2 ClusterRoles.
* Run the following commands to prepare the environment. **NOTE:** Make sure there are no other DSP installations in the testing cluster:
```
$ export IMAGE=quay.io/<QUAY_USERNAME>/dspo:v2
$ export DSPO_NS=data-science-pipelines-operator-v2
$ export DSPA_NS=data-science-pipelines-application-v2
$ oc new-project $DSPO_NS
$ oc new-project $DSPA_NS
$ make podman-build podman-push IMG=$IMAGE
$ make v2deploy IMG=$IMAGE V2INFRA_NS=openshift-pipelines
$ make deploy IMG=$IMAGE …
```
> Adding back run and task related permissions

- config/internal/apiserver/sample-pipeline.yaml.tmpl
- controllers/testdata/declarative/case_2/expected/created/sample-pipeline.yaml.tmpl
- docs/example_pipelines/condition.yaml
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/375
Replacing hardcode references to minio-service endpoints with an environment variable.
* Build an image with changes in this PR. This is the image I built with these changes: `quay.io/rhn_support_ddalvi/data-science-pipelines-operator:minio-revised`
* Deploy DSPO and create a DSPA instance
* Make sure minio pod comes up correctly
* Create a run using the default pipeline to make sure it goes through correctly.
> Adding a variable for minio-service endpoint

- controllers/database.go
- controllers/dspipeline_controller.go
- controllers/storage.go
- controllers/storage_test.go
- controllers/suite_test.go
Resolves #451 
Extracted DB and Object Storage Error Logs which were only visible in DSPO to display on DSPA Conditions with a brief message of any error.
1. Deploy DSPO
2. Deploy a Minio in a self-signed external OCP cluster (preferablly different from the dsp host cluster) 
```
oc new-project minio
oc -n minio apply -f https://gist.githubusercontent.com/HumairAK/f1358278ab70dde2ee074d1a35f8f058/raw/f234ba638f408c3aff8ed836858d0d1e332f43be/minio.yaml
$MINIO_ROUTE=$(oc get routes -n minio minio-secure --template={{.spec.host}})
```
3. On DSP host cluster, deploy a dspa, first without the cabundle:
```
kind: Secret
apiVersion: v1
metadata:
name: s3secret
namespace: dspa
stringData:
customaccessKey: accesskey
customsecretKey: secretkey
type: Opaque
---
apiVersion: …
```
> Extracted DB and Object Storage Error Logs to display on DSPA

- config/internal/apiserver/service.yaml.tmpl
Resolves #490 
This small PR wraps the Oauth port in the APIServer's Service object behind the `.APIServer.EnableRoute` flag so that if a DSPA is created with `spec.apiServer.enableOauth=false`, this port will not exist in the service. 
Tested with `IMG=quay.io/cgarriso/data-science-pipelines-operator:service-oauth` 
Deployed DSPO, created a sample DSPA with 
```
spec:
apiServer:
enableOauth: false
```
and ensured that port:
```
- name: oauth
port: 8443
protocol: TCP
targetPort: oauth
```
is not present in the service. 
Similarly, created DSPA with `enableOauth: true` and ensured that the port was in the service.
> Add flag to APIServer service's oauth port

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/mariadb/pvc.yaml.tmpl
- config/internal/minio/pvc.yaml.tmpl
- config/samples/custom-configs/dspa.yaml
Resolves #192
1. Added StorageClassName field under minio and mariaDB sections in the CRD and in minio & mariaDB structs.
2. Added StorageClassName in the PVC template file for minio and mariaDB.
-  Deploy DSPO and create a dspa instance using the dspa.yaml file in this path- config/samples/custom-configs.
-  Check the storageClassName assigned with default value by looking at the pvc created for minio and mariaDB.
-  dspa.yaml file can be edited with a different storageClassName to see if its getting assigned.
* The commits are squashed in a cohesive manner and have meaningful messages.
* Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
* The developer has manually tested the changes and verified that the changes work
> Added storageClassName in the PVCs for Minio and MariaDB

- config/internal/mariadb/pvc.yaml.tmpl
- config/internal/minio/pvc.yaml.tmpl
> Correct pvc storageclass indentation.

- config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
- controllers/testdata/declarative/case_7/expected/created/sample-pipeline.yaml.tmpl
Resolves #personal annoyances :) 
Add default values to the input parameters of the v2 sample pipeline such that they are auto-filled
deploy DSPO. Create V2 DSPA, wait for it to be fully ready
Run the pre-loaded sample pipeline, verify that the input parameters (min_max_scaler=true, neighbors=3, standard_scalar=false)*
Note that standard_scalar seems to not pre-fill correctly, but this is due to a seperate bug (TODO: add link) where 'False' default values are simply not loaded.
> Add default values for v2 sample pipeline input parameters

- controllers/storage.go
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/528
Improves the error message to explicitly say which attribute to use in the CR to specify the CA Bundle for the self-signed / untrusted certificate for the Object Store.
Setup the local Object Store (e.g. minio, see https://ai-on-openshift.io/tools-and-applications/minio/minio/) with the self-signed certificate and then attempt to use such Object Store as exernal Object Store. The error message should appear, indicating the exact attribute to use to specify the CA Bundle (should be `spec.apiServer.cABundle`).
> Update DSP API Server cABundle error msg

- config/internal/apiserver/role_pipeline-runner.yaml.tmpl
- config/rbac/role.yaml
- controllers/dspipeline_controller.go
The MCAD group seems to have been taken out of the [codeflare-operator rbac](https://github.com/project-codeflare/codeflare-operator/commit/f5bc3c1e51dc5c4e2c1e77b39da6963499510211). Updating DSPO RBCs to reflect the same and make the RBACs consistent.
> Remove mcad.ibm.com APIGroup

- docs/release/compatibility.yaml
Resolves #496
Updated compatibility.yaml file with argo supported versions
Run the following command to see if it reflects the changes in compatibility.md
```
python release.py version_doc --input_file compatibility.yaml --out_file compatibility.md
```
> Document supported Argo versions for v2

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/default/deployment.yaml.tmpl
- config/internal/apiserver/default/kfp_launcher_config.yaml.tmpl
- config/samples/external-object-storage/dspa.yaml
- controllers/dspipeline_params.go
Resolves [RHOAIENG-1707](https://issues.redhat.com//browse/RHOAIENG-1707)
DSPO will now deploy a kfp-launcher config to accomodate: https://github.com/opendatahub-io/data-science-pipelines/pull/4
Thus allowing dspa's to be deployed in multiple namespaces, and not just restricted to kubeflow namespace 
DSPA: 
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
metadata:
name: sample1
namespace: dspa3
spec:
dspVersion: v2
apiServer:
deploy: true
image: quay.io/hukhan/ds-pipelines-api-server:pr-4
argoLauncherImage: quay.io/hukhan/kfp-launcher:pr-4
argoDriverImage: quay.io/hukhan/kfp-driver:pr-4
persistenceAgent:
deploy: true
image: gcr.io/ml-pipeline/persistenceagent:2.0.2
scheduledWorkflow:
deploy: true
image: …
```
> add kfp-launcher config support.

- config/internal/minio/default/service.yaml.tmpl
- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- config/samples/dspa_simple_v2.yaml
- controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
This is a work around for the kfp ui to be able to read artifacts within the preview section. KFP UI will not accept port specifications for the s3 generic config, it will default to port 80 or 443 for http/https connections, since our default minio is port 80, we have to enable that port, as well as add the aws required s3 generic env vars to kfp ui deployment.
> enable kfp ui to retrieve artifacts.

- go.mod
Resolves [RHOAIENG-2259](https://issues.redhat.com/browse/RHOAIENG-2259)
Fixing go.mod dependencies/packages related snyk CVEs.
Imported my fork in synk and made sure the relevant CVEs were fixed with this update.
> Fix go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp CVE

- config/internal/apiserver/default/service.ml-pipeline.yaml.tmpl
Resolves  https://issues.redhat.com/browse/RHOAIENG-2798
This solves a race condition that existed because of a workaround we've implemented. KFP exposes a service that is backed by the apiserver pod. In Data Science Pipelines, we want this service name to be dynamic -- `ds-pipeline-{ DSPA NAME }}`. In KFP v2, the running pipeline pods call back to the apiserver via its service, and they rely on the hardcoded service name of `ml-pipeline` (https://github.com/kubeflow/pipelines/issues/9689). To temporarily work around this hardcoding, we're exposing both services -- our dynamically-named one and the hardcoded `ml-pipeline` one. (Both services point to the same apiserver pod.)
We use the [OpenShift service ca operator](https://docs.openshift.com/container-platform/4.12/security/certificates/ …
> fix: remove conflicting tls proxy secret generator.

- config/v2/cache/clusterrole.yaml
- config/v2/exithandler/clusterrole.leaderelection.yaml
- config/v2/exithandler/controller/clusterrole.clusteraccess.yaml
- config/v2/exithandler/controller/clusterrole.tenantaccess.yaml
- config/v2/kfptask/clusterrole.leaderelection.yaml
- config/v2/kfptask/webhook/clusterrole.clusteraccess.yaml
- config/v2/pipelineloop/clusterrole.leaderelection.yaml
- config/v2/pipelineloop/controller/clusterrole.tenantaccess.yaml
Resolves [RHOAIENG-1680](https://issues.redhat.com/browse/RHOAIENG-1680)
This PR removes kind/resource type mentions from metadata.name in resources
Just normal Sanity checks
> Remove kind/resource type mentions from metadata.name in resources

- config/internal/minio/route.yaml.tmpl
- config/samples/dspa_healthcheck.yaml
- controllers/dspipeline_params.go
- controllers/storage.go
Resolves [RHOAIENG-1643](https://issues.redhat.com//browse/RHOAIENG-1643)
Leverage the Object store external route to perform the Health check.
Deploy DSPO
```
make deploy IMG=quay.io/opendatahub/data-science-pipelines-operator:pr-519
```
Deploy DSPA instance using dspa_healthcheck.yaml file and check the logs to see if the Minio object store health check is successful.
Note: Please create a CA bundle to avoid custom cert issues while testing and update the same under apiServer section as show in the dspa_healthcheck.yaml file. Created configmap with ca cert as shown below:
kind: ConfigMap
apiVersion: v1
metadata:
name: my-ca
data:
ca.crt: |
> Leverage ObjStore Routes for Prereq Health Checks

- .github/resources/argo-lite/kustomization.yaml
- .github/resources/argo-lite/patch/argo_server_deployment.yaml
- config/argo/deployment.argo-server.yaml
- config/argo/params.yaml
- config/base/kustomization.yaml
- config/base/params.env
- config/configmaps/kustomization.yaml
- config/overlays/make-argodeploy/argo-server-image-patch.yaml
- config/overlays/make-argodeploy/kustomization.yaml
- config/overlays/rhoai/kustomization.yaml
Related: https://issues.redhat.com/browse/RHOAIENG-2877
Provide a rhoai overlay alongside an odh overlay
This will allow us to patch any rhoai specific changes in the future
Also add argo server image to params.env so odh operator can sub this in for downstream.
One change here to watch out is the change to the configmapGenerator suffix, this makes it so that the 2 configmaps created for the DSPO deployment no longer have the hash suffix.
* confirm kustomize builds in the overlay directories build as expected, and that argo image is subbed in
* `make deployODH` behavior should not have changed other than the configmap name change, the output should be otherwise the same 
* currently the rhoai overlay should function identically to the odh overlay
> feat: add rhoai overlay.

- config/base/kustomization.yaml
- config/base/params.env
- config/manager/manager.yaml
- controllers/config/defaults.go
- controllers/dspipeline_controller.go
Resolves https://issues.redhat.com/browse/RHOAIENG-2099
Same as: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/571 for v1.6
> feat: have pre-req retry upon check fail

- config/internal/mlpipelines-ui/deployment.yaml.tmpl
Livness probe via exec / wget seems flakey and seems to result in kfp ui crashing: 
Despite the kfp UI working fine, this ends up restarting the pod and causing it to sporadically go into crashloop.
> chore: update mlpipelines ui liveness/readiness to use http.

- controllers/dspipeline_params.go
`odh-trusted-ca-bundle` can have empty ca-bundle fields, we need to account for this, and ignore them if these are found, for consistency we treat user provided ca bundles the same way.
> chore: ignore empty cabundle fields.

- config/internal/apiserver/default/service.yaml.tmpl
- config/internal/mlpipelines-ui/service.yaml.tmpl
Service serving certificate annotations were changed from `alpha` to `beta` 3 years ago. Fixing.
Ref: https://github.com/openshift/openshift-docs/commit/847d4dcbd7934bf6b20040231b5b607c1065c73b
> chore: fix serving cert annotations

- .github/resources/argo-lite/kustomization.yaml
- Makefile
- README.md
- config/overlays/make-argodeploy/kustomization.yaml
- config/overlays/make-deploy/img_patch.yaml
- config/overlays/make-deploy/kustomization.yaml
This pr fixes the broken `make deploy IMG=` option, and it also allows `make deploy` to deploy the full v2 stack, including argo, eliminating the need for `deployODH` and `argoDeploy` options.
run `make deploy`, and `make deploy IMG=<custom-image>`, and make sure they work as intended.
> chore: allow make deploy to fully deploy v2 stack

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/default/deployment.yaml.tmpl
- controllers/testdata/declarative/case_0/deploy/cr.yaml
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
Resolve: https://issues.redhat.com/browse/RHOAIENG-4382
Merge after this is merged: https://github.com/opendatahub-io/data-science-pipelines/pull/23
enableSamplePipeline should be off by default, and users should opt in to use it 
* Deploy DSPO with changes 
* deploy DSPA without `spec.apiServer.enableSamplePipeline` set and ensure no pipeline shows up: 
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
metadata:
name: sample
spec:
dspVersion: v2
objectStorage:
minio:
deploy: true
image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
mlpipelineUI:
image: quay.io/opendatahub/ds-pipelines-frontend:latest
```
* then deploy another dspa with enable `spec.apiServer.enableSamplePipeline=true`, and …
> Disable samples by default

- config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
- config/rbac/role.yaml
- controllers/dspipeline_controller.go
Resolves [RHOAIENG-880](https://issues.redhat.com/browse/RHOAIENG-880)
Added the additional permissions which was missing and is required to create ray clusters. 
1. Create a Data Science project with namespace "pipelineskfptekton1"
2. Create a valid pipeline server
3. Import the pipeline mentioned below
4. Run the pipeline
5. It should work without any errors.
<details>
<summary>pipeline.yaml</summary>
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
name: ray-integration-test
annotations:
tekton.dev/output_artifacts: '{"ray-fn": [{"key": "artifacts/$PIPELINERUN/ray-fn/Output.tgz",
"name": "ray-fn-Output", "path": "/tmp/outputs/Output/data"}]}'
tekton.dev/input_artifacts: '{}'
tekton.dev/artifact_bucket: mlpipeline
tekton.dev/artifact_endpoint: minio-service.kubeflow:9000 …
```
> Added the additional permissions in the pipeline runner file for Ray

- config/internal/apiserver/default/server-config.yaml.tmpl
- controllers/testdata/declarative/case_0/expected/created/configmap_server_config.yaml
- controllers/testdata/declarative/case_6/expected/created/configmap_server_config.yaml
Resolves: https://issues.redhat.com/browse/RHOAIENG-4509
for v2
Use the defaults provided via kfp for pipelines store path, also use the same log archive defaults.
For the pipelines, this setting ensure pipelines in obj store are organized under the `pipelines` folder in obj store, instead of the root (which would get messy). 
Confirm for both v1 and v2. 
1. Deploy a v1 dspa, upload a pipeline, confirm this pipeline is stored in the `/pipelines` folder in the object store
2.  you can do this by using the default minio, creating a route to minio, logging in (creds are in secrets) to the ui
3. Do the same for v2 (in a new namespace, or clean up the existing one)
> chore: use pipelines default pipeline store path

- controllers/config/manifest.go
- controllers/config/templating.go
Currently we panic and crash the operator if templating fails, this is not ideal., the controller should be resilient to errors and forward them up the call stack and log them.
> fix: fail templating gracefully

- config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
- controllers/testdata/declarative/case_7/expected/created/sample-pipeline.yaml.tmpl
- docs/example_pipelines/iris/iris-pipeline.py
- docs/example_pipelines/iris/iris-pipeline.yaml
Resolves #annoyance
standard_scaler and min_max_scaler were effectivly mutually exclusive, so let's implement them as such to work around the issue with false-y default input params not parsing/instantiating correctly on the kfp UI.
Deploy DSPO, create a v2 DSPA with `spec.apiServer.enableSamplePipeline` = true.  Create a run of the sample pipeline and ensure that all input parameters are populated and you can simply click 'run' without specifying anything else.  Extra credit for also setting 'standard_scaler' to false and ensuring pipeline still runs with the MinMaxScaler instead of StandardScaler
> Simplify sample pipeline input parameters

- Makefile
- tests/README.md
- tests/dspa_v2_test.go
- tests/experiments_test.go
- tests/pipeline_test.go
- tests/suite_test.go
- tests/util/resources.go
- tests/util/rest.go
Resolves https://issues.redhat.com/browse/RHOAIENG-1672
Convert integration tests to leverage testify instead of gomega/ginkgo.
Deploy DSPO. In a fresh namespace, run the following command:
```
go test ./... --tags=test_integration -v -kubeconfig=${KUBECONFIG_PATH} -k8sApiServerHost=${TARGET_CLUSTER}   -DSPANamespace=${TARGET_NAMESPACE} -DSPAPath=resources/dspa-lite.yaml
```
For the impatient developer, you can use the following flag to skip DSPA install. This is useful when you want to make changes to a live environment and run the tests against it:
```
go test ./... --tags=test_integration -v -kubeconfig=${KUBECONFIG_PATH} -k8sApiServerHost=${TARGET_CLUSTER}   -DSPANamespace=${TARGET_NAMESPACE} -DSPAPath=resources/dspa-lite.yaml -skipDeploy=true -skipCleanup=true
```
> Refactor integration test suite to use testify

- .github/resources/mariadb/deployment.yaml
- .github/resources/mariadb/kustomization.yaml
- .github/resources/mariadb/pvc.yaml
- .github/resources/mariadb/secret.yaml
- .github/resources/mariadb/service.yaml
- .github/resources/minio/deployment.yaml
- .github/resources/minio/kustomization.yaml
- .github/resources/minio/pvc.yaml
- .github/resources/minio/secret.yaml
- .github/resources/minio/service.yaml
- .github/workflows/kind-integration.yml
- tests/dspa_v2_test.go
- tests/resources/dspa-external-lite.yaml
Resolves [RHOAIENG-1676](https://issues.redhat.com/browse/RHOAIENG-1676)
Added integration tests for external minio/mariadb connections in Github actions workflow.
Integration tests can be verified in the Github actions  workflow-KinD DSPO/DSP Integration Tests of this PR.
> Add integration tests for external storage/db connections

- Makefile
Have functest make command set the custom SSL_CERT_FILE path to leverage dummy cabundles
> chore: add ssl env to functest

- config/base/kustomization.yaml
- config/base/params.env
- config/manager/manager.yaml
Resolves [RHOAIENG-4256](https://issues.redhat.com//browse/RHOAIENG-4256)
Removes parameters that aren't used/duplicated by the DSPO.
Just build the DSPO image and deploy it with a valid DSPA object.
> Remove unnecessary DSPO parameters

- config/internal/common/argo/policy.yaml.tmpl
- config/internal/common/tekton/policy.yaml.tmpl
Resolves https://issues.redhat.com/browse/RHOAIENG-4546
Replace the existing generic dashboard label in the network policy's pod selector with [the new exclusive static notebook pod label.
](https://github.com/opendatahub-io/kubeflow/pull/265)
Deploy DSPO + DSPA.
Deploy ODH Dashboard and Workbenches in the same namespace as that of the DSPA instance.
From the notebook pod, try this curl command:
`curl http://<data-science-pipelines-service-hostname>:8888/apis/v1beta1/runs`
This command should return a JSON response with details about the existing pipeline runs. If no runs exist, you'll still see the structure of the response, confirming that the API endpoint is accessible and functioning.
> Adding exclusive notebook pod label

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_6/deploy/03_cr.yaml
- controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_6/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_6/expected/created/configmap_dspa_trusted_ca.yaml
- controllers/testdata/declarative/case_6/expected/created/metadata_grpc_deployment.yaml
- controllers/testdata/declarative/case_8/deploy/02_cr.yaml
- controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_8/expected/created/configmap_artifact_script.yaml
- controllers/testdata/declarative/case_8/expected/created/configmap_dspa_trusted_ca.yaml
Resolves [RHOAIENG-3780](https://issues.redhat.com/browse/RHOAIENG-3780)
- Added new parameter for caBundleFileMountPath which can be set by users in dspa. 
- Overrides the values of default values of CustomCABundleRootMountPath and customDSPTrustedCAConfigMapKey, if the values are provided in dspa.
Deploy a self-signed  cert minio and provide these configs to the DSPA as external storage connection.
Deploy dspa using the below yaml file (with your updated details for minio).Create a pipeline run and verify the mount paths in kfp-launcher pod and pipeline server to see the ca-bundle mountpath that we provided in the dspa.
```
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
metadata:
name: sample
spec:
dspVersion: v2
apiServer: …
```
> Parameterize CABundle mountpath in dspa

- config/internal/common/default/mlmd-envoy-dashboard-access-policy.yaml.tmpl
- config/internal/common/no-owner/clusterrolebinding.yaml.tmpl
- config/internal/ml-metadata/metadata-envoy.deployment.yaml.tmpl
- config/internal/ml-metadata/metadata-envoy.route.yaml.tmpl
- config/internal/ml-metadata/metadata-envoy.service.yaml.tmpl
- config/internal/ml-metadata/metadata-envoy.serviceaccount.yaml.tmpl
- controllers/testdata/declarative/case_5/expected/created/metadata-envoy_deployment.yaml
Resolves [RHOAIENG-4921](https://issues.redhat.com/browse/RHOAIENG-4921)
To adhere to the security requirements, this PR adds OAuth2 proxy as sidecar to MLMD envoy proxy.
* Deploy DSPO
* Deploy DSPO from `config/samples/v2/dspa-simple/dspa_simple.yaml`
* Check if `ds-pipeline-metadata-envoy-sample` pod has both envoy and oauth2-proxy containers
> Add oauth2-proxy in mlmd envoy proxy pod

- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
This PR fixes a description that is automatically generated. This probably was caused by a missing file in a previous commit.
1. Checkout the main branch.
2. Run `make functest`
3. Run `git status` and you'll see this update.
1. Checkout this branch
2. Run `make functest`
3. Run `git status`. No changes must be shown.
> Updated description in datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml

- tests/resources/Dockerfile
- tests/resources/test-pipeline-run.yaml
- tests/resources/test-pipeline-src.py
gcs is a supported path in kfp, adding it here for parity
> chore: add gcs folder to ci exec img.

- config/overlays/odh/argo/kustomization.yaml
- config/overlays/odh/dspo/kustomization.yaml
- config/overlays/rhoai/argo/kustomization.yaml
- config/overlays/rhoai/dspo/kustomization.yaml
Resolves [RHOAIENG-5243](https://issues.redhat.com/browse/RHOAIENG-5243)
Added overlays for deploying dspo and argo separately
Normal Sanity checks to see if everything is working as it should.
> RHOAIENG-5243 - Added overlays for deploying dspo and argo separately

- config/manager/manager.yaml
Resolves [RHOAIENG-1669](https://issues.redhat.com/browse/RHOAIENG-1669)
Leveraging **Vertical Pod Autoscaling recommender** , I got values suggested for the request size to be a bit more when I had a single DSPA deployed along with DSPO. 
I took the safe route of taking the minimum suggested values to modify the request size for manager by the Jira Reporter instead as it is recommended to leverage **Vertical Pod Autoscaling** for atleast a week before considering the suggested values.
1. Deploy DSPO
2. Deploy DSPA and see if the sample pipeline works as it should.
> RHOAIENG-1669 - Modified the Request Size for Manager

- tests/pipeline_runs_test.go
- tests/util/rest.go
Resolves [RHOAIENG-4720](https://issues.redhat.com/browse/RHOAIENG-4720)
Adding Integration tests to create an iris pipeline run and testing its successful completion.
Please follow the instructions from [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/tests/README.md#full-test-suite) to run the integration tests.
> RHOAIENG-4720 -Add an integration test that runs iris pipeline to completion

- config/internal/common/default/mariadb-access-policy.yaml.tmpl
- config/manager/manager.yaml
- controllers/dspipeline_params.go
Resolves [RHOAIENG-5314](https://issues.redhat.com/browse/RHOAIENG-5314)
Added new Network policy which allows DSPO  to resolve connections to  mariadb deployed in the user namespace.
1. Deploy DSPO and create a DSPA. Run a pipeline and it should complete successfully.
2. Verify  the Network Policies in DSPA namespace, to see a new NWP for mariadb. Eg. mariadb-simple
> Added new Network Policy to access Mariadb from DSPO

- config/internal/ml-metadata/metadata-envoy.route.yaml.tmpl
- config/internal/ml-metadata/metadata-envoy.service.yaml.tmpl
Resolves [RHOAIENG-5348](https://issues.redhat.com/browse/RHOAIENG-5348)
1. Updated the metadata envoy route name to avoid the issue with creation of pipeline server when the project name is longer than 31 chars.
2. This is the route name before the change - https://ds-pipeline-metadata-envoy-dspa-MYPROJECT.apps.clustername.domain.com/  , when the project name is longer than 31 chars pipeline server fails to create. Updated the route to this format - https://ds-pipeline-md-myproject.apps.clustername.domain.com/ which allows the project name to have more chars.
Deploy DSPO and create a DSPA instance. The metadata envoy route should be as shown in the below format-
https://ds-pipeline-md-myproject.apps.clustername.domain.com/
> Updated metadata envoy route name

- config/internal/ml-metadata/metadata-envoy.serviceaccount.yaml.tmpl
- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
Resolves [RHOAIENG-5348](https://issues.redhat.com/browse/RHOAIENG-5348)
- Updated mlpipelines-ui deployment file with the updated metadata-envoy service host . 
- Updated metadata-envoy-serviceaccount with the new service name.
Created this PR to fix the below error in kfp-ui which was caused by the changes done with this PR-https://github.com/opendatahub-io/data-science-pipelines-operator/pull/650-
Error occurred while trying to proxy request /ml_metadata.MetadataStoreService/GetContextByTypeAndName from ds-pipeline-ui-sample-dspa1.apps.rosa.hukhan.wrh7.p3.openshiftapps.com to http://ds-pipeline-metadata-envoy-sample:9090/ (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Deploy DSPO and create a DSPA instance. Create a pipeline run and make sure there are no …
> FIX - Update metadata envoy service name in mlpipelines-ui deployment file

- controllers/apiserver_test.go
- controllers/dspastatus/dspa_status.go
- controllers/dspipeline_controller.go
- controllers/persistence_agent_test.go
- controllers/scheduled_workflow_test.go
- controllers/workflow_controller.go
Resolves https://issues.redhat.com/browse/RHOAIENG-6287
This PR refactors `controllers.DSPAReconciler#Reconcile` so it updates the DSPA status correctly.
- Deploy `config/samples/v2/dspa-simple` to the `kubeflow` namespace.
- Wait until all the pods get started.
```
oc get pods -n kubeflow
NAME                                                      READY   STATUS    RESTARTS   AGE
ds-pipeline-metadata-envoy-sample-5857b74974-psjcd        2/2     Running   0          49s
ds-pipeline-metadata-grpc-sample-79995d8b76-8rg8c         1/1     Running   0          49s
ds-pipeline-persistenceagent-sample-69c64c4cf-8bgvl       1/1     Running   0          50s
ds-pipeline-sample-7975c7f99-b5fl5                        2/2     Running   0          50s
ds-pipeline-scheduledworkflow-sample-bc6f4c55d-prfbz …
```
> Fixed the DSPA status update on reconciliation

- config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
Resolves https://issues.redhat.com/browse/RHOAIENG-7346
Adds route.openshift.io->routes->get, list permissions
No testing should be necessary here, but these permissions fixed the codeflare-sdk running using pipelines
For DW verification:
```
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/654/head
git checkout -b pullrequest c025c7243bb58166df4471d5b416ddf83cedfd98
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-654"
```
Configure the pipeline server and create default `LocalQueue` in the opendatahub.
Upload this https://issues.redhat.com/secure/attachment/13193837/pipeline.yaml and run the pipeline.
Should not get credential errors from …
> Added routes permissions to pipeline runner

- config/internal/mlpipelines-ui/deployment.yaml.tmpl
- controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/mlpipelines-ui_deployment.yaml
- controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
this disables the gke ui bits from loading in the kfp ui
> disable gke metadata in kfp ui

- tests/README.md
- tests/pipeline_runs_test.go
- tests/util/rest.go
Resolves https://issues.redhat.com/browse/RHOAIENG-7657
This PR improves handling for non-found pipelines and runs.
KinD DSPO/DSP Integration Tests must always pass.
> Fixed flaky test IntegrationTestSuite#TestPipelineSuccessfulRun

- .github/scripts/tests/kind-integration.sh
- .github/workflows/kind-integration.yml
Resolves [RHOAIENG-9518](https://issues.redhat.com/browse/RHOAIENG-9518)
Create a shared testing artifact for DSPO infrastructure
* Add `- '.github/workflows/kind-integration.yml'` as part of this PR because changing the yaml must also run the steps
* All environment variables are defined in the script. The script requires two environment variables `GIT_WORKSPACE` and `REGISTRY_ADDRESS`. They can change based on the host. While running in GHA they have a value while running locally they have other value.
* The job has a lot of steps. The `name` was translated to a comment. The `env` were defined early in the script. The `working-directory` is translated to ( cd ... && ... )
* We can now use the script locally and on Jenkins
Have a kind cluster and execute the bash with the two required …
> Move embedded binary and bash calls from YAML to a single script

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- controllers/config/defaults.go
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_9/expected/created/apiserver_deployment.yaml
Increase expiry for signed url to recommended minimum from aws s3
> increase default expiry for signed url

- .github/workflows/kind-integration.yml
- Makefile
Resolves [RHOAIENG-10819](https://issues.redhat.com//browse/RHOAIENG-10819)
Replace the `kustomize` binary with `$(KUSTOMIZE)`
It is automated by `KinD DSPO/DSP Integration Tests / dspo-tests (pull_request)`
> Consolidate kustomize binaries in DSPO Makefile

- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/default/kfp_launcher_config.yaml.tmpl
- config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
- controllers/dspipeline_params.go
- controllers/dspipeline_params_test.go
- controllers/testutil/util.go
Resolves https://issues.redhat.com/browse/RHOAIENG-4528
Allow the user to fully replace the `data` contents of the kfp-launcher ConfigMap. The `kfp-launcher` component requires a ConfigMap to exist in the namespace where it runs (i.e. the namespace where pipelines run). This ConfigMap contains object storage configuration, as well as pipeline root (object store root path where artifacts will be uploaded) configuration. Currently this ConfigMap *must* be named "kfp-launcher". We currently deploy a default copy of the kfp-launcher ConfigMap via DSPO, but a user may want to provide their own ConfigMap configuration, so that they can specify multiple object storage sources and paths.
Add a `CustomKfpLauncherConfigMap` parameter to DSPA.ApiServer. When specified, the `data` contents of the …
> add ability to customize `kfp-launcher` ConfigMap data contents

- controllers/dspipeline_controller.go
n/a
Clarify the "DSPA not found" log message that happens when a DSPA is deleted
n/a
> Clarify the "DSPA not found" log message that happens when a DSPA is deleted

- config/internal/ml-metadata/metadata-grpc.networkpolicy.yaml.tmpl
Resolves [RHOAIENG-10994](https://issues.redhat.com/browse/RHOAIENG-10994)
Added a network policy for MLMD GRPC Server.
-  Deploy DSPO, create a dspa instance and verify if a network policy gets created for GRPC , eg. ds-pipeline-metadata-grpc-myproject.
-  Create a pipeline run to verify if it works properly.
-  Execute the below curl command from ds-pipeline-metadata-envoy-sample-myproject , it should connect successfully.
```curl -v ds-pipeline-metadata-grpc-myproject.<namespace>.svc.cluster.local:8080 ```
- Execution of  the same curl command from any other pod other than ds-pipeline-metadata-grpc or the driver/launcher pods should time out.
> Added MLMD GRPC Server Network Policy

- config/internal/ml-metadata/metadata-grpc.networkpolicy.yaml.tmpl
pipeline server also needs to be able to communicate with mlmd, making this NP more permissible to avoid any other unforseen issues, this will allow all dsp component pods to communicate with mlmd grpc server
> make mlmd grpc NP more permissive

- controllers/dspipeline_params.go
- tests/resources/dspa-external-lite.yaml
- tests/resources/dspa-lite.yaml
envoy route should be enabled by default, unless specified otherwise via dspa CR
> fix default envoy route behavior

- config/samples/v2/dspa-simple/dspa_simple.yaml
This is needed when `enableExternalRoute=true` because the dev minio is behind a re-encrypt route and, on a self-signed ocp cluster, will serve certs signed by ocp network operator, which requires the client to have the kuberoot ca trust
> add kuberoot-ca to sample

- .github/workflows/build-prs-trigger.yaml
- .github/workflows/release_trigger.yaml
This PR updates `upload-artifact` action due to deprecation. The current version [is blocking PRs](https://github.com/opendatahub-io/data-science-pipelines-operator/actions/runs/10905399912/job/30264134931?pr=683).
Deprecation notice: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
The `Trigger build images for PRs / upload-data (pull_request)` workflow should pass.
> Bumped actions/upload-artifact to v4

- .github/scripts/tests/tests.sh
- .github/workflows/kind-integration.yml
- .gitignore
Break down the solution for #[RHOAIENG-10212](https://issues.redhat.com//browse/RHOAIENG-10212) into smaller PRs to facilitate review.
The goal of `test.sh --rhoai` is to be to run the DSPO test suite with a previous RHOAI installed.
* Have an OpenShift cluster with RHOAI installed and in the terminal do the following
* oc login ...
* export GIT_WORKSPACE=.....
* test.sh --rhoai
The output must be
```
--- PASS: TestIntegrationTestSuite (350.21s)
--- PASS: TestIntegrationTestSuite/TestAPIServerDeployment (1.89s)
--- PASS: TestIntegrationTestSuite/TestAPIServerDeployment/Should_successfully_fetch_pipelines (0.47s)
--- PASS: TestIntegrationTestSuite/TestAPIServerDeployment/Should_successfully_upload_a_pipeline (0.91s)
--- PASS: TestIntegrationTestSuite/TestAPIServerDeployment/Should_successfu …
```
> Allow DSPO test suite be running with RHOAI

- config/internal/mariadb/default/service.yaml.tmpl
- config/internal/mariadb/default/tls-config.yaml.tmpl
- controllers/database.go
- controllers/dspipeline_params.go
- controllers/testdata/declarative/case_8/expected/created/mariadb_deployment.yaml
Resolves #[RHOAIENG-4972](https://issues.redhat.com//browse/RHOAIENG-4972)
- Updated MariaDB config to server over TLS.
- Added the oc annotation to generate the certs.
- Added a config map with the ssl info.
- Deploy DSPO and the dspa using the below yaml file for two scenarios. After deployment, verify that the health 
checks are successful.
- Create a pipeline run and ensure that it completes successfully.
- Execute the following command inside the MariaDB pod terminal to verify that the TLS setup is correctly configured.
```
mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h 127.0.0.1 -D $MYSQL_DATABASE
MariaDB [mlpipeline]> SHOW GLOBAL VARIABLES LIKE 'have_ssl';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| have_ssl      | YES   |
+---------------+-------+
1 …
```
> Updated mariadb to serve over tls

- .github/scripts/tests/tests.sh
Break down the solution for #[RHOAIENG-10212](https://issues.redhat.com//browse/RHOAIENG-10212) into smaller PRs to facilitate review.
* Introducing the `CLEANUP` flag allows for optional resource cleanup before the tests. Useful while retrying the test in the OpenShift environment. The final cleanup solution will be discussed in other PR.
* The `K8SAPISERVERHOST` variable provides more flexibility, enabling it to be set via a command line argument, rather than being hardcoded within the test functions."
* Removed `DSPA_NAME` and `DSPA_EXTERNAL_NAME` as redundant variables, simplifying namespace handling by directly using `DSPA_NAMESPACE` and `DSPA_EXTERNAL_NAMESPACE`. This removes unnecessary duplication.
* Replaced the use of `kubectl whoami --show-server` for `K8SAPISERVERHOST` in the …
> Support environment variables as parameter

- .github/scripts/python_package_upload/Dockerfile
- .github/scripts/python_package_upload/package_upload.sh
- .github/scripts/python_package_upload/package_upload_run.sh
- .github/scripts/tests/tests.sh
- .gitignore
- tests/resources/test-pipeline-run.yaml
- tests/resources/test-pipeline-with-custom-pip-server-run.yaml
- tests/resources/test-pipeline-with-custom-pip-server.py
- tests/resources/test-pipeline.py
Resolves https://issues.redhat.com/browse/RHOAIENG-13915
- **pip download**: This command fetches packages and their dependencies without installing them. It is crucial that the version of Python for which the packages are downloaded matches the version in the target runtime environment. If you run `pip download` in an environment with Python 3.9, but your target system uses Python 3.10, there could be incompatibilities.
- **pip install**: This installs the downloaded packages into the runtime environment. Without a Dockerfile, installation can be influenced by the host environment’s Python version, leading to mismatches between the development, testing, and production environments.
1. **Replacement of boto3 with numpy**. It has low dependency artifacts.
2. **Environment-Agnostic Package …
> Replace boto3 with numpy

- .github/scripts/tests/tests.sh
- tests/dspa_v2_test.go
- tests/experiments_test.go
- tests/pipeline_runs_test.go
- tests/pipeline_test.go
- tests/resources/dspa-external.yaml
- tests/resources/dspa.yaml
- tests/suite_test.go
- tests/util/rest.go
Resolves partially [RHOAIENG-10212](https://issues.redhat.com//browse/RHOAIENG-10212)
This PR introduces enhancements to the test suite by allowing the use of either a route or a Kubernetes service as the target endpoint for interacting with the Data Science Pipelines Operator (DSPO).
1. **New `--endpointType` Flag**:
- A new `--endpointType` flag is introduced in the test suite configuration, which specifies whether the test should use a Kubernetes service (`service`) or an OpenShift route (`route`) as the target endpoint for DSPO.
2. **Infrastructure Cleanup Option**:
- The `--cleanup` flag is renamed to `--clean-infra`. This option allows automated cleanup of infrastructure before rerunning tests.
3. **Modifications in Test Scripts**:
- Updated the shell scripts and Go test files to …
> Add support for using route or service as target endpoints in the test suite

- config/internal/common/argo/policy.yaml.tmpl
The DSP apiserver implements TLS by relying on the OpenShift service cert signer. In order to get this to work nicely with our openshift-oauth sidecar, we set the Kubernetes service as the upstream for the oauth container. This means that all incoming traffic to DSP goes like this:
`client -> DSP service -> DSP oauth -> DSP service -> DSP apiserver` 
DSP oauth and DSP apiserver are in the same pod. We haven't explicitly created a NetworkPolicy to allow that, but it works on AWS and OpenStack-based clusters. For some yet to be determined reason, it doesn't work on IBM / Calico / Secure-By-Default clusters.
Add a NetworkPolicy entry to allow the DSP pod to talk to itself on 8888 and 8887. This fixes the issue where DSP(oauth) can't talk to DSP(apiserver) via the service (that fronts both …
> fix: add NetworkPolicy for DSP apiserver pod self traffic

- controllers/dspipeline_controller.go
This will now follow the debug log level when set via zap logging options 
this will avoid the spam of: 
```
"DSPA resource was not found, assuming it was recently deleted, nothing to do here"
```
log messages in the info level here https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L22
and as described [here](https://github.com/opendatahub-io/data-science-pipelines-operator?tab=readme-ov-file#configuring-log-levels-for-the-operator)
> switch dspa resource not found err to debug

- controllers/dspipeline_controller.go
When a dspa is marked for deletion, there is no state logic to handle dspa statuses, so the update can at times try to update a dspa that may have already been deleted, this change should prevent (or reduce) the chances of this happening, in the future proper/graceful dspa termination handling should be added. 
The following error appears when you try to delete the dspa, it may not always show up, it depends on reconcile timing and k8s server response:
```
2024-10-18T17:10:32-04:00       ERROR   Encountered error when updating the DSPA status {"namespace": "dspa2", "dspa_name": "sample", "error": "Operation cannot be fulfilled on datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io \"sample\": StorageError: invalid object, Code: 4, Key: …
```
> prevent dspa status update on a terminating dspa

- README.md
- config/configmaps/files/config.yaml
- controllers/config/defaults.go
- controllers/testdata/README.md
- controllers/testdata/declarative/case_0/config.yaml
- controllers/testdata/declarative/case_1/config.yaml
- controllers/testdata/declarative/case_2/config.yaml
- controllers/testdata/declarative/case_3/config.yaml
- controllers/testdata/declarative/case_4/config.yaml
- controllers/testdata/declarative/case_5/config.yaml
- controllers/testdata/declarative/case_6/config.yaml
- tests/dspa_v2_test.go
this will match the config path to what we are specifying for env vars
for the pa image found in config/base/params.env i.e.
IMAGES_PERSISTENCEAGENT should match Images.PersistenceAgent
> correct pa config path

- docs/release/compatibility.md
- docs/release/compatibility.yaml
The oauth-proxy version was bumped to v4.14 in https://github.com/opendatahub-io/data-science-pipelines-operator/pull/725
> Update oauth-proxy version in compatiblity table for 2.8

- config/internal/persistence-agent/deployment.yaml.tmpl
This PR must be merged with https://github.com/opendatahub-io/data-science-pipelines/pull/96
Resolves https://issues.redhat.com/browse/RHOAIENG-13871
This PR adds validation of MLMD and Persistence Agent server certificates against CA in the clients.
There are 2 scenarios:
1. Deploy the following DSPA:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
metadata:
name: sample
spec:
dspVersion: v2
apiServer:
enableSamplePipeline: true
podToPodTLS: true
image: quay.io/opendatahub/ds-pipelines-api-server:pr-96
argoDriverImage: quay.io/opendatahub/ds-pipelines-driver:pr-96
argoLauncherImage: quay.io/opendatahub/ds-pipelines-launcher:pr-96
cABundle:
configMapKey: ca.crt
configMapName: kube-root-ca.crt
persistenceAgent:
deploy: true …
```
> Use DSPA custom ca cert on MLMD and Persistence Agent clients

- controllers/database.go
GoDoc-style comment for your tLSClientConfig function
NA
> Improve documentation for tLSClientConfig

- tests/dspa_v2_test.go
- tests/resources/test-pipeline-run.yaml
- tests/resources/test-pipeline-with-custom-pip-server-run.yaml
Resolves #[RHOAIENG-15760](https://issues.redhat.com//browse/RHOAIENG-15760)
Bump KFP to 2.10.0. The tests that are using the pip server were downloaded 2.10.0 and the yaml has 2.9.0. Due to that the test simulates the air-gap environment. The test was failing.
I also changed the timeout. Sometimes it will take more than 10 seconds and iterating every 2ms is not feasible. Each operation take more time than that.
NA
> Bump DSPO test suite to KFP 2.10.0

- controllers/dspipeline_params.go
Resolves https://issues.redhat.com/browse/RHOAIENG-15689
Added `TrimSpace` when checking if certificates are empty.
See https://issues.redhat.com/browse/RHOAIENG-15689.
> Trimmed certificates before checking them

- .github/scripts/tests/tests.sh
Partial resolves #[RHOAIENG-15407](https://issues.redhat.com//browse/RHOAIENG-15407)
Print the error if the variable REGISTRY_ADDRESS is not defined
Execute `sh .github/scripts/tests/tests.sh --kind` and you should see the error
> Print if REGISTRY_ADDRESS is not defined

- .github/scripts/tests/README.md
> Document test.sh

- api/v1/dspipeline_types.go
- api/v1alpha1/dspipeline_types.go
- config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
- config/internal/apiserver/default/deployment.yaml.tmpl
- config/internal/apiserver/sample-pipeline/sample-config.yaml.tmpl
- controllers/apiserver.go
- controllers/dspipeline_params.go
- tests/pipeline_test.go
- tests/resources/dspa-lite.yaml
- tests/resources/test-pipeline-run.yaml
- tests/resources/test-pipeline-with-custom-pip-server-run.yaml
- tests/util/rest.go
Resolves #<[RHOAIENG-16507](https://issues.redhat.com/browse/RHOAIENG-16507)>
- Added support for provisioning the iLab pipeline as part of a DSPA deployment.
- Introduced a new parameter, ```enableIlabKFPPipeline```(set to false by default), which can be set to true to enable the iLab KFP pipeline in the UI.
- Deploy DSPO.
- Deploy  DSPA using the provided yaml file:
- Scenario 1:
Provision both the Iris and InstructLab pipelines, create pipeline runs, and ensure they complete successfully.
```
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
metadata:
name: sample
spec:
dspVersion: v2
apiServer:
enableSamplePipeline: true
enableInstructlabPipeline: true
image: quay.io/opendatahub/ds-pipelines-api-server:pr-120
cABundle:
configMapKey: …
```
> Add ilab kfp pipeline to the DSPO repo

- scripts/release/params.py
To keep it consistent with the latest config, we should really just reference the config in config/base/parsme.env instead to avoid having to do this. 
The shas are syncing with what's in main params
https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env
> update params to match latest configs

- config/manager/manager.yaml
this should override the config: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/28b1a5b4872dd2418977ab5a8a53738cb5662472/controllers/apiserver.go#L60
> correct dspo platformversion

- config/internal/apiserver/default/deployment.yaml.tmpl
- controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
- controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Init and Main container should have access to the same env vars
To do this:
- Move all env vars to Init container
- Mark the env section with `&apiserverEnvs` anchor
- Reference `*apiserverEnvs` in main container env section rather than duplicating
1. Deploy DSPO.
2. Deploy DSPA.
3. Verify `env` sections are identical in `init-pipelines` and `ds-pipeline-api-server` containers in newly created API Server pod
> Provide APIServer init and main Containers with same envs

- .github/resources/mariadb/deployment.yaml
- config/component_metadata.yaml
- config/internal/scheduled-workflow/deployment.yaml.tmpl
Resolves https://issues.redhat.com/browse/RHOAIENG-17788
This PR depends on: 
- https://github.com/opendatahub-io/data-science-pipelines/pull/142
Integration tests are expected to fail due to the dependency on https://github.com/opendatahub-io/data-science-pipelines/pull/134.
```
===== Pod: ds-pipeline-scheduledworkflow-test-dspa-68df7959c-8jqv2 in test-dspa =====
----- EVENTS -----
Events:
Type     Reason     Age                   From               Message
----     ------     ----                  ----               -------
Normal   Scheduled  3m18s                 default-scheduler  Successfully assigned test-dspa/ds-pipeline-scheduledworkflow-test-dspa-68df7959c-8jqv2 to cluster-control-plane
Normal   Pulled     2m59s                 kubelet            Successfully pulled image …
```
> Added support for TLS to scheduled-workflow

- .github/scripts/python_package_upload/package_download.sh
- .github/workflows/kind-integration.yml
The pipelines use KFP 2.11.0 so we need that version to be present on the PyPi server.
> Pin the KFP version in the custom PyPi integration test

- config/internal/apiserver/default/role_ds-pipeline.yaml.tmpl
If the run is associated with a ScheduledWorkflow and the OwnerReferencesPermissionEnforcement admission controller is on (default in OpenShift), it requires the update verb on scheduledworkflows/finalizers to set the proper owner reference.
Relates:
https://issues.redhat.com/browse/RHOAIENG-23606
https://github.com/kubeflow/pipelines/pull/11821
The easiest way is to create a recurring run that always uses the latest pipeline version.
> Fix run submissions with OwnerReferencesPermissionEnforcement on
